/* Unified inventory and recipe screens built from supplied documents and live management data. */
(function(){
const originalRender=window.renderOperations,REF=window.OPERATIONS_REFERENCE_V208||{inventory:[],recipes:[]};
const esc=value=>window.safeHtml?window.safeHtml(value):String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
const icon=name=>/원두|커피/.test(name)?"☕":/우유|밀크|크림/.test(name)?"🥛":/시럽|소스|청|베이스/.test(name)?"🧴":/과일|딸기|망고|자몽|멜론|레몬|라임/.test(name)?"🍓":/컵|뚜껑|빨대|봉투|포장|용기/.test(name)?"🥤":/팝콘/.test(name)?"🍿":/빵|베이글|케이크|떡|슈/.test(name)?"🥐":"📦";
const num=value=>Number(value||0).toLocaleString("ko-KR");
const cleanExample=value=>String(value||"").replace(/^\s*\[예시\]\s*/,"");
let inventoryCategory="전체",inventoryQuery="",purchaseOrders=[],recipeCategory="전체",recipeQuery="",managedInventory=[],registeredRecipes=[],hqProducts=[],hqInventory=[],hqRemovalMode=false,hqRemovalCategory="전체",hqRemovalSort="name";
const hqRemovalSelection=new Set();

function shell(title,subtitle){
  const root=document.getElementById("view");
  root.innerHTML='<div class="ops-head page-title-row"><div><h2 class="page-title">'+esc(title)+'</h2><p>'+esc(subtitle)+'</p></div></div><div id="opsBody"></div>';
  return document.getElementById("opsBody");
}
function modal(title,content){
  const wrap=document.createElement("div");
  wrap.className="ops-modal";
  wrap.innerHTML='<div class="ops-modal-sheet ops-unified-sheet"><div class="ops-modal-head"><b>'+esc(title)+'</b><button type="button" aria-label="닫기">×</button></div><div class="ops-modal-body">'+content+'</div></div>';
  document.body.appendChild(wrap);
  const close=()=>wrap.remove();
  wrap.querySelector(".ops-modal-head button").onclick=close;
  wrap.onclick=e=>{if(e.target===wrap)close()};
  return {wrap,body:wrap.querySelector(".ops-modal-body"),close};
}

async function loadInventoryManagement(){
  const [overview,manual]=await Promise.all([BE.inventoryOverview().catch(()=>[]),BE.inventoryManualList().catch(()=>[])]);
  const manualNames=new Set(manual.map(x=>x.name));
  const live=overview.filter(x=>!x.is_demo&&!/^\[예시\]/.test(x.name||"")&&!manualNames.has(x.name));
  purchaseOrders=await BE.inventoryPurchaseOrders().catch(()=>[]);
  managedInventory=[...manual.map(x=>({...x,on_hand:Number(x.on_hand||0),target_level:Number(x.target_level||0),reorder_point:Number(x.reorder_point||0),manual:true})),...live.map(x=>({...x,target_level:Number(x.reorder_level||0),reorder_point:Number(x.reorder_point||Number(x.reorder_level||0)*.65)}))];
}
function stockState(row){
  const on=Number(row.on_hand||0),target=Number(row.target_level||row.reorder_level||0),point=Number(row.reorder_point||0);
  if(point>0&&on<point*.5)return {key:"critical",label:"긴급 부족",rank:0};
  if(point>0&&on<=point)return {key:"low",label:"발주 필요",rank:1};
  return {key:"ok",label:"적정",rank:2};
}
function receivingPanel(){
  if(!purchaseOrders.length)return "";
  return '<section class="ops-order-panel ops-receiving-panel"><div class="ops-unified-section-head"><div><b>입고 대기</b><span>'+purchaseOrders.length+'건</span></div></div><div class="ops-order-bars">'+purchaseOrders.map((o,i)=>'<button type="button" class="ops-order-row" data-receive-order="'+i+'"><span><b>'+esc(o.item_name)+'</b><small>발주 '+num(o.ordered_quantity)+' '+esc(o.unit)+' · 입고 '+num(o.received_quantity)+' · 남음 '+num(Number(o.ordered_quantity)-Number(o.received_quantity))+'</small></span><strong>'+(o.status==="PARTIAL"?"부분 입고":"입고 처리")+'</strong></button>').join("")+'</div></section>';
}
async function openReceiveOrder(order){
 const remain=Number(order.ordered_quantity)-Number(order.received_quantity),m=modal("입고 처리",'<div class="ops-recipe-editor"><p><b>'+esc(order.item_name)+'</b><br>발주 '+num(order.ordered_quantity)+' '+esc(order.unit)+' · 미입고 '+num(remain)+' '+esc(order.unit)+'</p><label>이번 입고 수량<input id="opsReceiveQty" type="number" min="0.01" max="'+remain+'" step="0.01" value="'+remain+'"></label><button type="button" class="btn btn-primary" id="opsReceiveSave">입고 확정</button></div>');
 m.body.querySelector("#opsReceiveSave").onclick=async()=>{const qty=Number(m.body.querySelector("#opsReceiveQty").value||0);if(qty<=0||qty>remain)return alert("입고 수량을 확인하세요.");try{await BE.inventoryReceive(order.id,qty);m.close();await loadInventoryManagement();renderInventory(true)}catch(e){alert("입고 처리 실패: "+e.message)}};
}
async function openPurchaseOrder(row){
 const target=Number(row.target_level||row.reorder_level||0),on=Number(row.on_hand||0),suggest=Math.max(1,target-on),m=modal("발주 등록",'<div class="ops-recipe-editor"><p><b>'+esc(row.name)+'</b><br>현재 '+num(on)+' '+esc(row.unit||"")+' · 목표 '+num(target)+' '+esc(row.unit||"")+'</p><label>발주 수량<input id="opsOrderQty" type="number" min="0.01" step="0.01" value="'+suggest+'"></label><label>메모<input id="opsOrderNote" placeholder="선택 입력"></label><button type="button" class="btn btn-primary" id="opsOrderSave">발주 등록</button></div>');
 m.body.querySelector("#opsOrderSave").onclick=async()=>{const qty=Number(m.body.querySelector("#opsOrderQty").value||0);if(qty<=0)return alert("발주 수량을 입력하세요.");try{await BE.inventoryPurchaseOrder(row,qty,m.body.querySelector("#opsOrderNote").value.trim());m.close();await loadInventoryManagement();renderInventory(true)}catch(e){alert("발주 등록 실패: "+e.message)}};
}
function orderPanel(){
  const low=managedInventory.filter(x=>stockState(x).rank<2).sort((a,b)=>stockState(a).rank-stockState(b).rank||Number(a.on_hand)-Number(b.on_hand));
  const bars=low.length?low.map((row,index)=>{const target=Number(row.target_level||row.reorder_level||0),on=Number(row.on_hand||0),need=Math.max(0,target-on),pct=target?Math.min(100,on/target*100):0,st=stockState(row);return '<button type="button" class="ops-order-row '+st.key+'" data-managed-stock="'+managedInventory.indexOf(row)+'"><span><b>'+esc(row.name)+'</b><small>'+st.label+' · 현재 '+num(on)+' / 목표 '+num(target)+' '+esc(row.unit||"")+'</small></span><i><em style="width:'+pct+'%"></em></i><strong>발주 '+num(need)+' '+esc(row.unit||"")+'</strong></button>'}).join(""):'<div class="ops-order-empty">현재 발주점에 도달한 등록 품목이 없습니다.</div>';
  return '<section class="ops-order-panel"><div class="ops-unified-section-head"><div><b>발주 필요</b><span>'+low.length+'개 품목</span></div><div><button type="button" class="btn btn-secondary btn-sm" id="opsInventoryBulk">일괄 등록</button><button type="button" class="btn btn-primary btn-sm" id="opsInventoryAdd">+ 재고 등록</button></div></div><div class="ops-order-bars">'+bars+'</div></section>';
}
function inventoryState(row){
  const target=Number(row.target_level||row.reorder_level||0),point=Number(row.reorder_point||target*.65),on=Number(row.on_hand||0),ratio=target>0?on/target:1;
  if(point>0&&on<point*.5)return {key:"critical",label:"긴급 부족",rank:0};
  if(point>0&&on<=point)return {key:"low",label:"발주 필요",rank:1};
  if(ratio<=1.25)return {key:"ok",label:"적정",rank:2};
  if(ratio<=1.6)return {key:"ample",label:"여유",rank:3};
  return {key:"over",label:"과다",rank:4};
}
function inventoryCard(row){
  const life=row.shelf_life||{},expiry=[life.storage_after&&"개봉 후 "+life.storage_after,life.expiry_after&&"상미 "+life.expiry_after,life.after_portion&&"소분·해동 "+life.after_portion].filter(Boolean).join(" · ");
  const norm=v=>String(v||"").toLowerCase().replace(/\\s+/g,"").replace(/[()（）·._\\-]/g,"");
  const live=managedInventory.find(x=>norm(x.name)===norm(row.name));
  const title='<div class="ops-stock-title"><span class="ops-inventory-thumb" aria-hidden="true">'+(live?.thumbnail_url?'<img src="'+esc(live.thumbnail_url)+'" alt="">':icon(row.name))+'</span><b>'+esc(row.name)+'</b></div>';
  if(live){
    const isSource=/^SRC-/i.test(live.sku||"");
    if(isSource){
      const current=live.source_current_text||row.current_text||"-",minimum=live.source_minimum_text||row.minimum_text||"-",order=live.source_order_text||row.order_text||"-",unit=live.source_unit_system||live.unit||row.unit||"";
      return '<article class="ops-stock-bar ops-stock-reference state-reference">'+title+'<span class="ops-stock-info-btn reference">현재고</span><div class="ops-stock-footer ops-stock-reference-footer"><span><b>'+esc(current)+'</b><small>현재고 · '+esc(unit)+'</small></span><span><b>'+esc(minimum)+'</b><small>최소재고</small></span></div><div class="ops-stock-reference-order"><span>주문 기준</span><b>'+esc(order)+'</b></div>'+(live.source_note||row.note?'<p>'+esc(live.source_note||row.note)+'</p>':"")+(expiry?'<small class="ops-stock-expiry">'+esc(expiry)+'</small>':"")+'</article>';
    }
    const target=Number(live.target_level||live.reorder_level||0),on=Number(live.on_hand||0),pct=target?Math.min(100,Math.max(0,on/target*100)):0,need=Math.max(0,target-on),st=inventoryState(live),unit=live.unit||"";
    return '<article class="ops-stock-bar ops-stock-reference state-'+st.key+'">'+title+'<span class="ops-stock-info-btn">'+st.label+'</span><div class="ops-stock-level"><i><em style="width:'+pct+'%"></em></i></div><div class="ops-stock-footer"><span class="ops-stock-count"><b class="stock-now '+st.key+'">'+num(on)+'</b><span> / '+num(target)+' '+esc(unit)+'</span></span><strong class="ops-stock-order '+st.key+'">'+(st.rank<2&&need>0?'발주 필요: '+num(need)+' '+esc(unit):"")+'</strong></div>'+(row.note?'<p>'+esc(row.note)+'</p>':"")+(expiry?'<small class="ops-stock-expiry">'+esc(expiry)+'</small>':"")+'</article>';
  }
  return '<article class="ops-stock-bar ops-stock-reference state-reference">'+title+'<span class="ops-stock-info-btn reference">기준 재고</span><div class="ops-stock-level reference"><i><em style="width:65%"></em></i></div><div class="ops-stock-footer ops-stock-reference-footer"><span><b>'+esc(row.current_text||"-")+'</b><small>현재 기준</small></span><span><b>'+esc(row.minimum_text||"-")+'</b><small>발주 기준</small></span></div><div class="ops-stock-reference-order"><span>주문</span><b>'+esc(row.order_text||"-")+'</b></div>'+(row.note?'<p>'+esc(row.note)+'</p>':"")+(expiry?'<small class="ops-stock-expiry">'+esc(expiry)+'</small>':"")+'</article>';
}
function openInventoryEditor(item=null){return window.openInventoryEntry("manual",item,()=>renderInventory());}
function openInventoryBulk(){return window.openInventoryEntry("bulk",null,()=>renderInventory());}
async function renderInventory(refresh=false){
  const body=refresh?document.getElementById("opsBody"):shell("재고","발주 필요 품목과 현재 지점 재고 기준을 한 화면에서 관리합니다.");
  if(typeof window.mountAdminSubnav==="function") await window.mountAdminSubnav("inventory");
  if(!refresh)await loadInventoryManagement();
  const all=REF.inventory||[],categories=["전체",...new Set(all.map(x=>x.category))];let rows=inventoryCategory==="전체"?all:all.filter(x=>x.category===inventoryCategory);
  if(inventoryQuery)rows=rows.filter(x=>[x.name,x.current_text,x.minimum_text,x.order_text,x.note].some(v=>String(v||"").toLowerCase().includes(inventoryQuery)));
  body.innerHTML=orderPanel()+receivingPanel()+'<div class="ops-unified-section-title"><b>재고 기준</b><span>'+rows.length+'개</span></div><div class="ops-inventory-toolbar ops-reference-toolbar"><label>검색<input id="opsReferenceInventorySearch" type="search" value="'+esc(inventoryQuery)+'" placeholder="품목명·현재고·발주기준"></label><label>카테고리<select id="opsReferenceInventoryCat">'+categories.map(x=>'<option '+(x===inventoryCategory?'selected':'')+'>'+esc(x)+'</option>').join("")+'</select></label></div><div class="ops-stock-chart ops-stock-grid">'+(rows.length?rows.map(inventoryCard).join(""):'<div class="ops-empty"><b>검색 결과가 없습니다.</b></div>')+'</div>';
  document.getElementById("opsInventoryAdd").onclick=()=>openInventoryEditor();document.getElementById("opsInventoryBulk").onclick=openInventoryBulk;
  body.querySelectorAll("[data-managed-stock]").forEach(button=>button.onclick=()=>openPurchaseOrder(managedInventory[Number(button.dataset.managedStock)]));
  body.querySelectorAll("[data-receive-order]").forEach(button=>button.onclick=()=>openReceiveOrder(purchaseOrders[Number(button.dataset.receiveOrder)]));
  const search=document.getElementById("opsReferenceInventorySearch");search.oninput=e=>{inventoryQuery=e.target.value.trim().toLowerCase();renderInventory(true);const next=document.getElementById("opsReferenceInventorySearch");next.focus();next.setSelectionRange(next.value.length,next.value.length)};
  document.getElementById("opsReferenceInventoryCat").onchange=e=>{inventoryCategory=e.target.value;renderInventory(true)};
}

async function loadRegisteredRecipes(){registeredRecipes=(await BE.recipeList().catch(()=>[])).map(row=>({...row,menu_name:cleanExample(row.menu_name)}))}
function recipeThumbnail(row){
  const label=((window.TENANT_CONFIG?.reference_data?.category_thumbnails||{})[row?.category]||"MENU"),url=String(row?.thumbnail_url||"").trim();
  return '<div class="ops-recipe-thumb">'+(url?'<img src="'+esc(url)+'" alt="'+esc(row?.menu_name||"")+'" loading="lazy" data-thumb-fallback="'+esc(label)+'">':'<span>'+esc(label)+'</span>')+'</div>';
}
function recipeMeta(row){
  const map=window.TENANT_CONFIG?.reference_data?.category_labels||{};
  let category=map[row.category]||row.category||"레시피",name=String(row.menu_name||""),badges=[category];
  const batch=name.match(/\((\d+)잔(?:\s*분량)?\)/);
  if(row.category==="대용량 베이스"){badges=["대용량 베이스"+(batch?"("+batch[1]+"잔)":"")];name=name.replace(/\s*\(\d+잔(?:\s*분량)?\)\s*/," ").trim();}
  if(name==="추가 옵션"){badges=["푸드 조리","추가 옵션"];name=String(row.variants?.[0]?.label||"소시지 · 계란 후라이");}
  const ea=name.match(/\s*\((\d+EA(?:\s*\/\s*\d+EA)?)\)\s*$/i);let eaText="";if(ea){eaText=ea[1];name=name.slice(0,ea.index).trim();}
  return {badges,name,eaText};
}
function recipeCard(row,index,registered){
  const first=row.variants[0],preview=String(first?.content||"").split("\n").filter(Boolean).slice(0,3),meta=recipeMeta(row),thumbRow=registered?.thumbnail_url?registered:row;
  const badges=meta.badges.map((x,i)=>'<small class="ops-recipe-cat '+(i?"ops-recipe-cat-secondary":"")+'">'+esc(x)+'</small>').join("");
  return '<article class="ops-card ops-reference-recipe"><button type="button" class="ops-recipe-open" data-reference-recipe="'+index+'">'+recipeThumbnail(thumbRow)+'<div class="ops-reference-recipe-content"><div class="ops-card-head"><div><div class="ops-recipe-cats">'+badges+'</div><b>'+esc(meta.name)+(meta.eaText?'<small class="ops-recipe-ea">('+esc(meta.eaText)+')</small>':'')+'</b></div><span class="ops-reference-badge">'+row.variants.length+'종</span></div><div class="ops-recipe-variant-chips">'+row.variants.map(x=>'<span>'+esc(x.label)+'</span>').join("")+'</div><div class="ops-reference-preview">'+preview.map(x=>'<span>'+esc(x)+'</span>').join("")+'</div></div></button>'+(registered?'<button type="button" class="ops-recipe-edit" data-edit-recipe="'+registeredRecipes.indexOf(registered)+'" aria-label="'+esc(row.menu_name)+' 수정">✎</button>':"")+'</article>';
}
function customRecipeCard(row){
  const preview=(row.components||[]).slice(0,3).map(x=>esc(x.item_name||"재료")+' '+num(x.quantity)+' '+esc(x.unit||""));
  return '<article class="ops-card ops-reference-recipe ops-custom-recipe"><div class="ops-recipe-open ops-recipe-static">'+recipeThumbnail(row)+'<div class="ops-reference-recipe-content"><div class="ops-card-head"><div><small class="ops-recipe-cat">'+esc(row.category||"직접 등록")+'</small><b>'+esc(row.menu_name)+'</b></div><span class="ops-reference-badge">등록</span></div><div class="ops-reference-preview">'+preview.map(x=>'<span>'+x+'</span>').join("")+'</div></div></div><button type="button" class="ops-recipe-edit" data-edit-recipe="'+registeredRecipes.indexOf(row)+'" aria-label="'+esc(row.menu_name)+' 수정">✎</button></article>';
}
function openRecipeDetail(row){
  const m=modal(row.menu_name,'<div class="ops-recipe-variant-grid">'+row.variants.map(v=>'<section><h3>'+esc(v.label)+'</h3><div>'+esc(v.content).replace(/\n/g,"<br>")+'</div></section>').join("")+'</div>');m.wrap.querySelector(".ops-modal-sheet").classList.add("ops-reference-recipe-sheet");
}
async function fileToWebp(file){
  if(!/^image\/(jpeg|png|webp|gif)$/.test(file.type))throw Error("JPG, PNG, WEBP, GIF 이미지만 선택할 수 있습니다.");if(file.size>12*1024*1024)throw Error("이미지 파일은 12MB 이하만 선택할 수 있습니다.");
  return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error("파일을 읽을 수 없습니다."));reader.onload=()=>{const img=new Image();img.onerror=()=>reject(Error("이미지를 읽을 수 없습니다."));img.onload=()=>{const max=720,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/webp",.82))};img.src=String(reader.result)};reader.readAsDataURL(file)});
}
async function openRecipeEditor(recipe=null){
  const official=(REF.recipes||[]).find(x=>x.menu_name===cleanExample(recipe?.menu_name||""));
  const stock=await BE.inventoryOverview().catch(()=>[]),selected=new Map((recipe?.components||[]).map(x=>[Number(x.item_id),Number(x.quantity||0)]));
  if(!stock.length)return alert("레시피 재료로 선택할 재고 품목이 없습니다.");
  const ingredients=stock.map(x=>{const checked=selected.has(Number(x.id));return '<label class="ops-ingredient-row"><input type="checkbox" data-item="'+x.id+'" '+(checked?'checked':'')+'><span class="ops-ingredient-name"><b>'+esc(x.name)+'</b><small>잔고 '+num(x.on_hand)+' '+esc(x.unit)+'</small></span><input class="ops-ingredient-qty" type="number" min="0" step="0.01" data-qty="'+x.id+'" value="'+(checked?selected.get(Number(x.id)):"")+'" placeholder="사용량" '+(checked?'':'disabled')+'><em>'+esc(x.unit)+'</em></label>'}).join("");
  const sourceRecipe=official?'<section class="ops-source-recipe"><div class="ops-ingredient-head"><b>공식 제조 기준</b><span>원본 '+esc(official.source_version)+' · '+official.variants.length+'종</span></div><div class="ops-recipe-variant-grid">'+official.variants.map(v=>'<section><h3>'+esc(v.label)+'</h3><div>'+esc(v.content).replace(/\\n/g,"<br>")+'</div></section>').join("")+'</div></section>':"";
  const m=modal(recipe?"레시피 수정":"레시피 등록",'<div class="ops-recipe-editor">'+sourceRecipe+'<div class="ops-recipe-thumb-editor"><div class="ops-recipe-preview-wrap"><img id="unifiedRecipePreview" src="'+esc(recipe?.thumbnail_url||"")+'" alt=""></div><div><label>썸네일 URL<input id="unifiedRecipeThumbnail" value="'+esc(recipe?.thumbnail_url||"")+'" placeholder="https://..."></label><label class="btn btn-secondary btn-sm ops-thumb-file-btn">이미지 파일 선택<input id="unifiedRecipeFile" type="file" accept="image/jpeg,image/png,image/webp,image/gif" hidden></label></div></div><label>메뉴 카테고리<input id="unifiedRecipeCategory" value="'+esc(recipe?.category||"")+'"></label><label>메뉴명<input id="unifiedRecipeName" value="'+esc(recipe?.menu_name||"")+'"></label><div class="ops-ingredient-head"><b>재료 선택</b><span>현재 잔고 기준</span></div><div class="ops-ingredient-list">'+ingredients+'</div><button type="button" class="btn btn-primary" id="unifiedRecipeSave">'+(recipe?"수정 저장":"레시피 등록")+'</button></div>');
  const thumb=m.body.querySelector("#unifiedRecipeThumbnail"),preview=m.body.querySelector("#unifiedRecipePreview"),file=m.body.querySelector("#unifiedRecipeFile");thumb.oninput=()=>preview.src=thumb.value.trim();file.onchange=async()=>{try{thumb.value=await fileToWebp(file.files[0]);preview.src=thumb.value}catch(error){alert(error.message);file.value=""}};
  m.body.querySelectorAll("[data-item]").forEach(check=>check.onchange=()=>{const qty=m.body.querySelector('[data-qty="'+check.dataset.item+'"]');qty.disabled=!check.checked;if(check.checked&&!qty.value)qty.value="1"});
  m.body.querySelector("#unifiedRecipeSave").onclick=async()=>{const name=m.body.querySelector("#unifiedRecipeName").value.trim(),components=[...m.body.querySelectorAll("[data-item]:checked")].map(check=>({item_id:Number(check.dataset.item),quantity:Number(m.body.querySelector('[data-qty="'+check.dataset.item+'"]')?.value||0)})).filter(x=>x.quantity>0);if(!name)return alert("메뉴명을 입력하세요.");if(!components.length)return alert("재료를 하나 이상 선택하세요.");try{await BE.recipeSave(recipe?.id||null,name,m.body.querySelector("#unifiedRecipeCategory").value.trim(),components,thumb.value.trim());m.close();await loadRegisteredRecipes();renderRecipes(true)}catch(error){alert("레시피 저장 실패: "+error.message)}};
}
async function renderRecipes(refresh=false){
  const body=refresh?document.getElementById("opsBody"):shell("레시피","공식 제조 기준과 직접 등록한 레시피를 한 화면에서 관리합니다.");if(!refresh)await loadRegisteredRecipes();
  const official=REF.recipes||[],officialNames=new Set(official.map(x=>x.menu_name)),registeredByName=new Map(registeredRecipes.map(x=>[x.menu_name,x])),custom=registeredRecipes.filter(x=>!officialNames.has(x.menu_name));
  const categories=["전체",...new Set([...official.map(x=>x.category),...registeredRecipes.map(x=>x.category).filter(Boolean)])];let rows=recipeCategory==="전체"?official:official.filter(x=>x.category===recipeCategory),customRows=recipeCategory==="전체"?custom:custom.filter(x=>x.category===recipeCategory);
  if(recipeQuery){const matches=x=>[x.menu_name,x.category,...(x.variants||[]).map(v=>v.content),...(x.components||[]).map(v=>v.item_name)].some(v=>String(v||"").toLowerCase().includes(recipeQuery));rows=rows.filter(matches);customRows=customRows.filter(matches)}
  body.innerHTML='<div class="ops-unified-section-head ops-recipe-manage-head"><div><b>레시피 목록</b><span>등록 '+registeredRecipes.length+'개</span></div><button type="button" class="btn btn-primary btn-sm" id="opsRecipeAdd">+ 레시피 등록</button></div><div class="ops-recipe-toolbar ops-reference-toolbar"><label>검색<input id="opsReferenceRecipeSearch" type="search" value="'+esc(recipeQuery)+'" placeholder="메뉴명·재료·조리법"></label><label>메뉴 카테고리<select id="opsReferenceRecipeCat">'+categories.map(x=>'<option '+(x===recipeCategory?'selected':'')+'>'+esc(x)+'</option>').join("")+'</select></label></div><div class="ops-reference-count">'+esc(recipeCategory)+' · '+(rows.length+customRows.length)+'개</div><div class="ops-reference-recipe-list">'+customRows.map(customRecipeCard).join("")+(rows.length?rows.map((row,index)=>recipeCard(row,index,registeredByName.get(row.menu_name))).join(""):(customRows.length?'':'<div class="ops-empty"><b>검색 결과가 없습니다.</b></div>'))+'</div>';
  document.getElementById("opsRecipeAdd").onclick=()=>openRecipeEditor();body.querySelectorAll(".ops-recipe-thumb img").forEach(img=>img.onerror=()=>{const fallback=document.createElement("span");fallback.textContent=img.dataset.thumbFallback||"MENU";img.replaceWith(fallback)});body.querySelectorAll("[data-reference-recipe]").forEach(button=>button.onclick=()=>openRecipeDetail(rows[Number(button.dataset.referenceRecipe)]));body.querySelectorAll("[data-edit-recipe]").forEach(button=>button.onclick=e=>{e.stopPropagation();openRecipeEditor(registeredRecipes[Number(button.dataset.editRecipe)])});
  const search=document.getElementById("opsReferenceRecipeSearch");search.oninput=e=>{recipeQuery=e.target.value.trim().toLowerCase();renderRecipes(true);const next=document.getElementById("opsReferenceRecipeSearch");next.focus();next.setSelectionRange(next.value.length,next.value.length)};document.getElementById("opsReferenceRecipeCat").onchange=e=>{recipeCategory=e.target.value;renderRecipes(true)};
}

function hqStatus(status){return status==="ACTIVE"?"출시 중":status==="SCHEDULED"?"출시 예약":status==="DISCONTINUED"?"제거됨":"초안"}
function hqKstDate(value){if(!value)return "";return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value))}
function hqProductCard(row,index,selectable=false){
  const components=Array.isArray(row.component_blueprint)?row.component_blueprint:[],active=row.status==="ACTIVE",stopped=row.status==="DISCONTINUED",scheduled=row.status==="SCHEDULED",removalDate=hqKstDate(row.removal_scheduled_at),updateDate=active&&row.has_pending_changes?hqKstDate(row.scheduled_at):"",thumb=row.thumbnail_url?'<img src="'+esc(row.thumbnail_url)+'" alt="" draggable="false">':'<span aria-hidden="true">'+icon(row.name)+'</span>';
  const pending=active&&row.has_pending_changes===true,actions=selectable?'':'<button type="button" class="btn '+(active?(pending?'btn-primary':'btn-secondary'):'btn-primary')+' ops-hq-apply'+(pending?' is-pending':'')+'" data-hq-apply="'+index+'" data-action="LAUNCH" '+(active&&!pending?'disabled title="아직 배포하지 않은 변경사항이 없습니다."':'')+'>'+(active?'변경사항 전 지점 적용':'전 지점 '+(stopped?'재출시':'출시'))+'</button>';
  const select=selectable?'<input class="ops-hq-card-check" type="checkbox" data-hq-select="'+row.id+'" aria-label="'+esc(row.name)+' 삭제 선택" '+(hqRemovalSelection.has(Number(row.id))?'checked':'')+'>':'';
  return '<article class="ops-hq-product-card status-'+String(row.status||"draft").toLowerCase()+(selectable?' is-selectable':'')+'" data-hq-card-id="'+row.id+'">'+select+'<div class="ops-hq-product-main"><div class="ops-hq-thumb">'+thumb+'</div><div class="ops-hq-product-copy"><span class="ops-hq-status">'+hqStatus(row.status)+'</span>'+(updateDate?'<span class="ops-hq-update-badge">'+esc(updateDate)+' 수정 예약</span>':'')+(removalDate?'<span class="ops-hq-removal-badge">'+esc(removalDate)+' 삭제 예약</span>':'')+'<small>'+esc(row.product_key)+'</small><h3>'+esc(row.name)+'</h3><p>'+esc(row.category||"미분류")+' · 재료 '+components.length+'개'+(scheduled?' · '+esc(hqKstDate(row.scheduled_at))+' 출시':'')+'</p></div>'+(selectable?'':'<button type="button" class="ops-recipe-edit ops-hq-edit" data-hq-edit="'+index+'" aria-label="'+esc(row.name)+' 수정">✎</button>')+'</div><div class="ops-hq-alias"><small>매출 연결</small><span>'+esc((row.sale_aliases||[]).join(", ")||"미설정")+'</span><small>매입 연결</small><span>'+esc((row.purchase_aliases||[]).join(", ")||"미설정")+'</span></div>'+actions+'</article>';
}
async function openHqProductEditor(product=null){
  const m=modal(product?"상품 수정":"신제품 등록",'<div class="ops-hq-loading"><span></span><b>재고 목록을 불러오는 중입니다.</b></div>');
  m.wrap.classList.add("ops-hq-editor-modal");
  m.wrap.addEventListener("dragstart",event=>event.preventDefault());
  if(!hqInventory.length)hqInventory=(await BE.inventoryOverview().catch(()=>[])).filter(x=>!x.is_demo).map(x=>({...x,name:cleanExample(x.name)}));
  if(!hqInventory.length){m.body.innerHTML='<div class="ops-empty"><b>선택할 재고 품목이 없습니다.</b><span>재고를 먼저 등록한 뒤 다시 시도하세요.</span></div>';return}
  const source=Array.isArray(product?.component_blueprint)?product.component_blueprint:[],newItems=[],selected=new Map(),originalQuantity=new Map(),categories=[...new Set([...(REF.recipes||[]).map(x=>x.category),...hqProducts.map(x=>x.category)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ko")),knownCategory=categories.includes(product?.category),categoryMode=product?.category&&!knownCategory?"new":"existing",scheduledDate=hqKstDate(product?.scheduled_at),isActive=product?.status==="ACTIVE",scheduleLabel=isActive?"수정 적용 예약일":"출시 예약일",scheduleHelp=isActive?"비워두면 변경사항만 저장하며, 지정하면 한국시간 해당 날짜 00:00에 전 지점에 자동 적용합니다.":"비워두면 즉시 출시하며, 지정하면 한국시간 해당 날짜 00:00에 자동 출시합니다.";
  source.forEach((component,index)=>{const existing=component.item_id?hqInventory.find(x=>Number(x.id)===Number(component.item_id)):hqInventory.find(x=>String(x.sku||"").toLowerCase()===String(component.sku||"").toLowerCase()),quantity=Number(component.quantity||0);if(existing){selected.set("i"+existing.id,quantity);originalQuantity.set("i"+existing.id,quantity)}else{const item={...component,_key:"n"+index};newItems.push(item);selected.set(item._key,quantity);originalQuantity.set(item._key,quantity)}});
  m.body.innerHTML='<div class="ops-hq-editor"><div class="ops-hq-fields"><label>상품 코드<input id="hqProductKey" value="'+esc(product?.product_key||"")+'" placeholder="예: SUMMER-MELON-2026"></label><label>상품명<input id="hqProductName" value="'+esc(product?.name||"")+'" placeholder="전 지점에 표시할 메뉴명"></label><div class="ops-hq-category"><span>카테고리</span><div class="ops-hq-category-mode"><label><input type="radio" name="hqCategoryMode" value="existing" '+(categoryMode==="existing"?'checked':'')+'> 기존 카테고리</label><label><input type="radio" name="hqCategoryMode" value="new" '+(categoryMode==="new"?'checked':'')+'> 새 카테고리 생성</label></div><select id="hqExistingCategory" '+(categoryMode==="existing"?'':'disabled')+'>'+categories.map(x=>'<option '+(x===product?.category?'selected':'')+'>'+esc(x)+'</option>').join("")+'</select><input id="hqNewCategory" value="'+(categoryMode==="new"?esc(product?.category||""):"")+'" placeholder="새 카테고리명" '+(categoryMode==="new"?'':'disabled')+'></div><label>매출 연결명<input id="hqSaleAliases" value="'+esc((product?.sale_aliases||[]).join(", "))+'" placeholder="POS 메뉴명, 쉼표로 구분"></label><label>매입 연결명<input id="hqPurchaseAliases" value="'+esc((product?.purchase_aliases||[]).join(", "))+'" placeholder="거래처·매입 품목명, 쉼표로 구분"></label><label class="ops-hq-launch-date">'+esc(scheduleLabel)+'<input id="hqLaunchDate" type="date" min="'+hqKstDate(Date.now()+86400000)+'" value="'+esc(scheduledDate)+'"><small>'+esc(scheduleHelp)+'</small></label></div><div class="ops-hq-component-head"><div><b>필요 재료 선택</b><small>기존 재고 또는 이번 출시에 함께 등록할 신규 재고를 선택하고 사용량을 지정합니다.</small></div><button type="button" class="btn btn-secondary btn-sm" id="hqNewInventory">+ 신규 재고 항목</button></div><input id="hqInventorySearch" class="ops-hq-inventory-search" type="search" placeholder="재고 품목 검색"><div id="hqInventoryPicker" class="ops-hq-inventory-picker"></div><div class="ops-hq-save-note">'+(isActive?'수정 예약일을 지정하면 판매 상태를 유지한 채 해당 날짜에 변경사항이 자동 적용됩니다.':'출시 예약일이 없으면 저장 즉시 전 지점에 출시됩니다.')+'</div><button type="button" class="btn btn-primary btn-block" id="hqProductSave">'+(scheduledDate?'예약 변경 저장':product?'변경사항 저장':'신제품 등록')+'</button></div>';
  const picker=m.body.querySelector("#hqInventoryPicker"),search=m.body.querySelector("#hqInventorySearch");
  const existingCategory=m.body.querySelector("#hqExistingCategory"),newCategory=m.body.querySelector("#hqNewCategory");
  m.body.querySelectorAll('[name="hqCategoryMode"]').forEach(radio=>radio.onchange=()=>{const useNew=radio.value==="new"&&radio.checked;existingCategory.disabled=useNew;newCategory.disabled=!useNew;if(useNew)newCategory.focus()});
  const collect=()=>picker.querySelectorAll("[data-hq-stock]").forEach(row=>{const key=row.dataset.hqStock,check=row.querySelector("input[type=checkbox]"),qty=row.querySelector(".ops-hq-stock-qty");if(check.checked)selected.set(key,Number(qty.value||0));else selected.delete(key)});
  const renderPicker=()=>{const q=search.value.trim().toLowerCase(),rows=[...hqInventory.map(x=>({key:"i"+x.id,item:x,isNew:false})),...newItems.map(x=>({key:x._key,item:x,isNew:true}))].filter(x=>!q||[x.item.name,x.item.sku,x.item.unit].some(v=>String(v||"").toLowerCase().includes(q)));picker.innerHTML=rows.length?rows.map(({key,item,isNew})=>{const current=originalQuantity.has(key)?'<small class="ops-hq-current-qty">현재 '+num(originalQuantity.get(key))+' '+esc(item.unit||"")+'</small>':'';return '<label class="ops-hq-stock-row '+(isNew?'is-new':'')+'" data-hq-stock="'+key+'"><input type="checkbox" '+(selected.has(key)?'checked':'')+'><span><b>'+esc(item.name)+'</b><small>'+(isNew?'신규 등록 · ':'')+esc(item.sku||"SKU 없음")+' · '+esc(item.unit||"")+'</small>'+current+'</span><span class="ops-hq-qty-editor"><small>'+(current?'수정값':'사용량')+'</small><input class="ops-hq-stock-qty" type="number" min="0.01" step="0.01" value="'+(selected.get(key)||"")+'" placeholder="사용량" '+(selected.has(key)?'':'disabled')+'></span><em>'+esc(item.unit||"")+'</em></label>'}).join(""):'<div class="ops-empty"><b>검색 결과가 없습니다.</b></div>';picker.querySelectorAll("[data-hq-stock]").forEach(row=>{const check=row.querySelector("input[type=checkbox]"),qty=row.querySelector(".ops-hq-stock-qty");check.onchange=()=>{qty.disabled=!check.checked;if(check.checked&&!qty.value)qty.value="1";collect()}})};
  renderPicker();search.oninput=()=>{collect();renderPicker()};
  m.body.querySelector("#hqNewInventory").onclick=()=>{const add=modal("신규 재고 항목",'<div class="ops-hq-new-stock"><label>SKU<input id="hqNewSku" placeholder="예: SYRUP-MELON"></label><label>품목명<input id="hqNewName" placeholder="예: 멜론 시럽"></label><label>단위<input id="hqNewUnit" placeholder="g, ml, 개"></label><label>발주 기준<input id="hqNewReorder" type="number" min="0" step="0.01" value="0"></label><button type="button" class="btn btn-primary" id="hqNewStockAdd">목록에 추가</button></div>');add.body.querySelector("#hqNewStockAdd").onclick=()=>{const get=id=>add.body.querySelector(id).value.trim(),sku=get("#hqNewSku"),name=get("#hqNewName"),unit=get("#hqNewUnit");if(!sku||!name||!unit)return alert("SKU, 품목명, 단위를 모두 입력하세요.");if([...hqInventory,...newItems].some(x=>String(x.sku||"").toLowerCase()===sku.toLowerCase()))return alert("이미 같은 SKU가 있습니다.");collect();const item={_key:"n"+Date.now(),sku,name,unit,reorder_level:Number(get("#hqNewReorder")||0)};newItems.push(item);selected.set(item._key,1);add.close();search.value="";renderPicker()}};
  m.body.querySelector("#hqProductSave").onclick=async()=>{collect();const split=id=>m.body.querySelector(id).value.split(",").map(x=>x.trim()).filter(Boolean),components=[...selected].map(([key,quantity])=>{if(key[0]==="i")return {item_id:Number(key.slice(1)),quantity};const item=newItems.find(x=>x._key===key);return item?{sku:item.sku,name:item.name,unit:item.unit,reorder_level:item.reorder_level,quantity}:null}).filter(Boolean),useNew=m.body.querySelector('[name="hqCategoryMode"]:checked').value==="new",category=(useNew?newCategory.value:existingCategory.value).trim(),launchDate=m.body.querySelector("#hqLaunchDate")?.value||"",payload={product_key:m.body.querySelector("#hqProductKey").value.trim(),name:m.body.querySelector("#hqProductName").value.trim(),category,sale_aliases:split("#hqSaleAliases"),purchase_aliases:split("#hqPurchaseAliases"),components};if(!payload.product_key||!payload.name)return alert("상품 코드와 상품명을 입력하세요.");if(!category)return alert("카테고리를 선택하거나 새로 입력하세요.");if(!components.length||components.some(x=>!x.quantity))return alert("필요 재료를 선택하고 모든 사용량을 입력하세요.");const button=m.body.querySelector("#hqProductSave");button.disabled=true;try{const savedId=await BE.hqProductSave(product?.id||null,payload);if(launchDate)await BE.hqProductSchedule(savedId,launchDate);else if(product?.scheduled_at||product?.status==="SCHEDULED")await BE.hqProductSchedule(savedId,null);else if(!product)await BE.hqProductApply(savedId,"LAUNCH");m.close();await renderHqProducts(document.querySelector(".ops-hq-fullscreen .ops-modal-body"))}catch(error){button.disabled=false;const message=String(error?.message||error);alert(message.includes("PRODUCT_HAS_NO_PENDING_CHANGES")?"예약할 변경사항이 없습니다. 상품 정보를 수정한 뒤 예약일을 지정하세요.":"상품 저장 실패: "+message)}};
}
async function applyHqProduct(product,action){
  if(!confirm(product.name+"을(를) 모든 활성 지점에 적용할까요?\n레시피·재고·매출/매입 연결이 함께 적용됩니다."))return;
  try{const result=await BE.hqProductApply(product.id,action);alert("적용 완료 · "+num(result?.affected_store_count)+"개 지점 반영");await renderHqProducts(document.querySelector(".ops-hq-fullscreen .ops-modal-body"))}catch(error){alert("적용 실패: "+error.message)}
}
function openHqRemovalChoice(body){
  const rows=hqProducts.filter(x=>hqRemovalSelection.has(Number(x.id))&&x.status==="ACTIVE");
  if(!rows.length)return alert("삭제할 제품을 선택하세요.");
  const tomorrow=hqKstDate(Date.now()+86400000),m=modal("제품 삭제 방식",'<div class="ops-hq-removal-choice"><p><b>'+rows.length+'개 제품</b>을 전 지점에서 삭제합니다.</p><label><input type="radio" name="hqRemovalType" value="now" checked><span><b>즉시 삭제</b><small>확인 즉시 전 지점 판매 목록에서 제거</small></span></label><label><input type="radio" name="hqRemovalType" value="scheduled"><span><b>예약 삭제</b><small>한국시간 지정일 00:00에 자동 제거</small></span></label><label class="ops-hq-removal-date">삭제 예약일<input id="hqRemovalDate" type="date" min="'+tomorrow+'" disabled></label><div class="ops-hq-remove-note">과거 매출·매입과 배포 이력은 보존됩니다.</div><button type="button" class="btn btn-danger btn-block" id="hqRemovalConfirm">삭제 적용</button></div>'),date=m.body.querySelector("#hqRemovalDate");
  m.body.querySelectorAll('[name="hqRemovalType"]').forEach(radio=>radio.onchange=()=>{date.disabled=radio.value!=="scheduled"||!radio.checked;if(!date.disabled&&!date.value)date.value=tomorrow});
  m.body.querySelector("#hqRemovalConfirm").onclick=async()=>{const type=m.body.querySelector('[name="hqRemovalType"]:checked').value,button=m.body.querySelector("#hqRemovalConfirm");if(type==="scheduled"&&!date.value)return alert("삭제 예약일을 선택하세요.");if(type==="now"&&!confirm(rows.map(x=>x.name).join(", ")+"을(를) 지금 전 지점에서 삭제할까요?"))return;button.disabled=true;try{if(type==="scheduled")await BE.hqProductRemovalSchedule(rows.map(x=>Number(x.id)),date.value);else for(const product of rows)await BE.hqProductApply(product.id,"DISCONTINUE");m.close();hqRemovalSelection.clear();hqRemovalMode=false;await renderHqProducts(body);alert(type==="scheduled"?"제품 삭제가 예약되었습니다.":"제품 삭제가 전 지점에 반영되었습니다.")}catch(error){button.disabled=false;alert("제품 삭제 실패: "+error.message)}};
}
function paintHqProducts(body){
  const activeRows=hqProducts.filter(x=>x.status==="ACTIVE"),active=activeRows.length,scheduled=hqProducts.filter(x=>x.status==="SCHEDULED").length,updateScheduled=activeRows.filter(x=>x.has_pending_changes&&x.scheduled_at).length,removalScheduled=activeRows.filter(x=>x.removal_scheduled_at).length,categories=["전체",...new Set(activeRows.map(x=>x.category||"미분류"))].sort((a,b)=>a==="전체"?-1:b==="전체"?1:a.localeCompare(b,"ko"));
  let rows=hqRemovalCategory==="전체"?activeRows:activeRows.filter(x=>(x.category||"미분류")===hqRemovalCategory);
  rows.sort((a,b)=>hqRemovalSort==="category"?String(a.category||"").localeCompare(String(b.category||""),"ko")||String(a.name).localeCompare(String(b.name),"ko"):hqRemovalSort==="recent"?new Date(b.updated_at)-new Date(a.updated_at):hqRemovalSort==="removal"?String(a.removal_scheduled_at||"9999").localeCompare(String(b.removal_scheduled_at||"9999")):String(a.name).localeCompare(String(b.name),"ko"));
  const toolbar=hqRemovalMode?'<div class="ops-hq-toolbar ops-hq-removal-toolbar"><div><button type="button" class="btn btn-secondary" id="hqRemovalCancel">취소</button><button type="button" class="btn btn-danger" id="hqRemovalProceed">선택 제품 삭제</button></div><small>삭제할 제품을 전체 또는 일부 선택하세요.</small></div>':'<div class="ops-hq-toolbar"><div><button type="button" class="btn btn-primary" id="hqProductAdd">+ 신제품 등록</button><button type="button" class="btn btn-danger" id="hqProductRemove">− 제품 삭제</button></div><small>출시·삭제 이력과 과거 거래는 보존됩니다.</small></div>';
  const controls=hqRemovalMode?'<div class="ops-hq-removal-controls"><label class="ops-hq-select-all"><input id="hqSelectAll" type="checkbox"><span>전체 선택 <small id="hqSelectionStatus">('+hqRemovalSelection.size+'개 선택 중)</small></span></label><label>카테고리<select id="hqRemovalCategory">'+categories.map(x=>'<option '+(x===hqRemovalCategory?'selected':'')+'>'+esc(x)+'</option>').join("")+'</select></label><label>정렬<select id="hqRemovalSort"><option value="name" '+(hqRemovalSort==="name"?'selected':'')+'>상품명순</option><option value="category" '+(hqRemovalSort==="category"?'selected':'')+'>카테고리순</option><option value="recent" '+(hqRemovalSort==="recent"?'selected':'')+'>최근 수정순</option><option value="removal" '+(hqRemovalSort==="removal"?'selected':'')+'>삭제 예약일순</option></select></label></div>':'';
  body.innerHTML=toolbar+'<div class="ops-hq-summary"><div><span>출시 중</span><b>'+active+'개</b></div><div><span>출시 예약</span><b>'+scheduled+'개</b></div><div><span>수정 예약</span><b>'+updateScheduled+'개</b></div><div><span>삭제 예약</span><b>'+removalScheduled+'개</b></div></div><div class="ops-hq-list-head"><b>출시 중인 상품</b><span>'+rows.length+'개</span></div>'+controls+'<div class="ops-hq-product-list">'+(rows.length?rows.map(row=>hqProductCard(row,hqProducts.indexOf(row),hqRemovalMode)).join(""):'<div class="ops-empty"><b>출시 중인 상품이 없습니다.</b></div>')+'</div>';
  if(hqRemovalMode){const count=()=>{body.querySelector("#hqSelectionStatus").textContent="("+hqRemovalSelection.size+"개 선택 중)";body.querySelector("#hqRemovalProceed").disabled=!hqRemovalSelection.size;const visible=rows.map(x=>Number(x.id)),selected=visible.filter(id=>hqRemovalSelection.has(id)).length,all=body.querySelector("#hqSelectAll");all.checked=visible.length>0&&selected===visible.length;all.indeterminate=selected>0&&selected<visible.length};body.querySelector("#hqRemovalCancel").onclick=()=>{hqRemovalMode=false;hqRemovalSelection.clear();paintHqProducts(body)};body.querySelector("#hqRemovalProceed").onclick=()=>openHqRemovalChoice(body);body.querySelector("#hqRemovalCategory").onchange=e=>{hqRemovalCategory=e.target.value;paintHqProducts(body)};body.querySelector("#hqRemovalSort").onchange=e=>{hqRemovalSort=e.target.value;paintHqProducts(body)};body.querySelector("#hqSelectAll").onchange=e=>{rows.forEach(x=>e.target.checked?hqRemovalSelection.add(Number(x.id)):hqRemovalSelection.delete(Number(x.id)));paintHqProducts(body)};body.querySelectorAll("[data-hq-select]").forEach(check=>check.onchange=()=>{const id=Number(check.dataset.hqSelect);check.checked?hqRemovalSelection.add(id):hqRemovalSelection.delete(id);check.closest(".ops-hq-product-card").classList.toggle("is-selected",check.checked);count()});count();return}
  body.querySelector("#hqProductAdd").onclick=()=>openHqProductEditor();body.querySelector("#hqProductRemove").onclick=()=>{if(!activeRows.length)return alert("삭제할 수 있는 제품이 없습니다.");hqRemovalMode=true;hqRemovalSelection.clear();paintHqProducts(body)};body.querySelectorAll("[data-hq-edit]").forEach(button=>button.onclick=()=>openHqProductEditor(hqProducts[Number(button.dataset.hqEdit)]));body.querySelectorAll("[data-hq-apply]").forEach(button=>button.onclick=()=>applyHqProduct(hqProducts[Number(button.dataset.hqApply)],button.dataset.action));
}
async function renderHqProducts(body){
  if(!body)return;body.innerHTML='<div class="ops-hq-loading"><span></span><b>상품 정보를 불러오는 중입니다.</b></div>';
  hqProducts=await BE.hqProductList().catch(error=>{body.innerHTML='<div class="ops-empty"><b>상품 정보를 불러오지 못했습니다.</b><span>'+esc(error.message)+'</span></div>';return null});if(!hqProducts)return;paintHqProducts(body);
}
window.openHqProductModal=()=>{if(window.STORE_ENTRY_LOCK)return;hqRemovalMode=false;hqRemovalSelection.clear();const m=modal("상품 배포",'<div class="ops-hq-loading"><span></span><b>상품 정보를 불러오는 중입니다.</b></div>');m.wrap.classList.add("ops-hq-fullscreen");renderHqProducts(m.body)};
window.renderOperations=async tab=>tab==="inventory"?renderInventory():tab==="recipe"?renderRecipes():originalRender(tab);
})();
