/* Payroll V1.3: contract-authoritative payroll + gross-first presentation. */
(()=>{
  if(globalThis.__franchisePayrollContractAuthorityV1)return;
  globalThis.__franchisePayrollContractAuthorityV1=true;
  if(typeof computeMonthPayroll!=='function'||typeof drawPay!=='function'||typeof calcPayroll!=='function')return;

  const baseComputeMonthPayroll=computeMonthPayroll;
  const baseDrawPay=drawPay;
  const baseOpenMonthAdjust=openMonthAdjust;
  const cache=new Map();
  const CACHE_TTL_MS=60000;
  let lastResult=null,refreshBusy=false;

  const p2=n=>String(n).padStart(2,'0');
  const dayKey=d=>d?`${d.getFullYear()}-${p2(d.getMonth()+1)}-${p2(d.getDate())}`:'';
  const monthBounds=ym=>{const [y,m]=String(ym).split('-').map(Number);return {first:`${ym}-01`,last:`${y}-${p2(m)}-${p2(new Date(y,m,0).getDate())}`}};
  const overlaps=(c,b)=>String(c.effective_from)<=b.last&&(!c.effective_to||String(c.effective_to)>=b.first);
  const covers=(c,d)=>d&&String(c.effective_from)<=d&&(!c.effective_to||String(c.effective_to)>=d);
  const termsKey=c=>[c.payroll_type,c.hourly_wage,c.monthly_salary,c.weekly_contracted_minutes,c.tax_treatment,c.business_deduction_rate,c.night_allowance_enabled,c.night_allowance_mode,c.night_allowance_value,c.night_allowance_start,c.night_allowance_end].join('|');

  function storedSession(){try{return JSON.parse(localStorage.getItem('franchise_auth')||'null')}catch(_){return null}}
  function saveSession(next){if(!next?.access_token)return;const prev=storedSession()||{};const merged={...prev,...next};localStorage.setItem('franchise_auth',JSON.stringify(merged));if(typeof Auth!=='undefined')Auth.token=merged.access_token}
  let refreshPromise=null;
  async function refreshSession(){
    if(refreshPromise)return refreshPromise;const s=storedSession();if(!s?.refresh_token)return null;
    refreshPromise=(async()=>{try{const r=await fetch(`${CONFIG.SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})});if(!r.ok)return null;const next=await r.json();saveSession(next);return next.access_token||null}catch(_){return null}finally{refreshPromise=null}})();return refreshPromise;
  }
  async function adminRpc(fn,args={}){const call=async token=>fetch(`${CONFIG.SUPABASE_URL}/rest/v1/rpc/${fn}`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${token||CONFIG.SUPABASE_ANON_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(args)});const s=storedSession();let token=(typeof Auth!=='undefined'&&Auth.token)||s?.access_token||null;let r=await call(token),text=await r.text();if(r.status===401||r.status===403||/JWT|NOT_AUTHORIZED|expired/i.test(text)){const fresh=await refreshSession();if(fresh){r=await call(fresh);text=await r.text()}}if(!r.ok)throw new Error(`RPC ${fn} ${r.status}: ${text||r.statusText}`);return text?JSON.parse(text):null}
  async function bundle(empId){const key=Number(empId),now=Date.now(),hit=cache.get(key);if(hit&&now-hit.at<CACHE_TTL_MS)return hit.value;const value=(await adminRpc('admin_employment_bundle',{p_employee_id:key}))||{contracts:[],periods:[],workdays:[]};cache.set(key,{value,at:now});return value}
  function safeOverride(ov){if(!ov)return null;const out={};if(ov.juhyu_weeks_override!=null)out.juhyu_weeks_override=ov.juhyu_weeks_override;if(ov.adjust_amount!=null)out.adjust_amount=ov.adjust_amount;if(ov.memo!=null)out.memo=ov.memo;return Object.keys(out).length?out:null}
  function chooseContract(row,ym,b){const contracts=(b.contracts||[]).filter(c=>overlaps(c,monthBounds(ym))).sort((a,z)=>String(z.effective_from).localeCompare(String(a.effective_from)));if(!contracts.length)return {mode:'MISSING_CONTRACT',issue:'계약조건 미등록 · 급여 계산 보류'};const payable=(row.sessions||[]).filter(s=>(s.status==='COMPLETE'||s.status==='WORKING')&&s.in);const used=contracts.filter(c=>payable.some(s=>covers(c,dayKey(s.in))));const candidates=used.length?used:contracts;const displayContract=candidates[0]||contracts[0]||null;if(candidates.some(c=>c.tax_treatment==='FOUR_INSURANCE'))return {mode:'BLOCKED',contract:displayContract,issue:'4대보험 공제 계산정책 미확정'};if(candidates.some(c=>c.payroll_type==='MONTHLY')){if(candidates.some(c=>c.payroll_type!=='MONTHLY'))return {mode:'BLOCKED',contract:displayContract,issue:'월중 급여유형 변경 · 구간별 급여 계산 확인 필요'};const keys=new Set(candidates.map(termsKey));if(keys.size>1)return {mode:'BLOCKED',contract:displayContract,issue:'월중 계약조건 변경 · 구간별 급여 계산 확인 필요'};return {mode:'MONTHLY',contract:candidates[0]};}if(candidates.some(c=>c.payroll_type!=='HOURLY'||c.tax_treatment!=='BUSINESS_INCOME'))return {mode:'BLOCKED',contract:displayContract,issue:'급여 계약조건 확인 필요'};const uncoveredDays=[...new Set(payable.filter(s=>!contracts.some(c=>covers(c,dayKey(s.in)))).map(s=>dayKey(s.in)))];if(uncoveredDays.length)return {mode:'BLOCKED',contract:displayContract,issue:`계약기간 밖 실근무 ${uncoveredDays.join(', ')} · 급여 확인 필요`};const keys=new Set(candidates.map(termsKey));if(keys.size>1)return {mode:'BLOCKED',contract:displayContract,issue:'월중 계약조건 변경 · 구간별 급여 계산 확인 필요'};return {mode:'CONTRACT',contract:candidates[0]}}
  function contractEmployee(emp,c){const weeklyMinutes=Number(c.weekly_contracted_minutes||0);return {...emp,wage:Number(c.hourly_wage||0),juhyu_hours:weeklyMinutes>=900?weeklyMinutes/60/5:0,tax_rate:Number(c.business_deduction_rate||0)}}
  function contractSummary(c){if(!c)return '';const period=`${c.effective_from}${c.effective_to?' ~ '+c.effective_to:''}`;if(c.payroll_type==='HOURLY')return `계약 시급 ${Number(c.hourly_wage||0).toLocaleString()}원 · ${period}`;return `계약 월급 ${Number(c.monthly_salary||0).toLocaleString()}원 · ${period}`}

  computeMonthPayroll=async function(ym){const R=await baseComputeMonthPayroll(ym);if(!LIVE){lastResult=R;return R;}let totalNet=0,totalGross=0;await Promise.all(R.rows.map(async row=>{try{const b=await bundle(row.employee_id),pick=chooseContract(row,ym,b);row.contractMode=pick.mode;row.contractIssue=pick.issue||null;row.contract=pick.contract||null;if(pick.mode==='CONTRACT'){/* Base computeMonthPayroll is authoritative for earned hourly pay, qualified weekly holiday, substitutions and adjustments. Do not recalculate here. */row.hasWage=!!row.pay;row.memo=(row.ov&&row.ov.memo)||row.emp.memo||''}else if(pick.mode==='MONTHLY'){row.hasWage=!!row.pay;row.memo=(row.ov&&row.ov.memo)||row.emp.memo||''}else if(pick.mode==='BLOCKED'||pick.mode==='MISSING_CONTRACT'){row.pay=null;row.hasWage=false}}catch(e){console.error('[payroll-contract-authority]',row.employee_id,e);row.contractMode='ERROR';row.contractIssue='계약조건 조회 실패 · 관리자 로그인 상태를 확인하세요.';row.contractError=String(e?.message||e)}if(row.pay){totalNet+=row.pay.net;totalGross+=row.pay.gross}}));R.totalNet=totalNet;R.totalGross=totalGross;lastResult=R;return R};

  function installStyle(){if(document.getElementById('payrollGrossFirstStyle'))return;const s=document.createElement('style');s.id='payrollGrossFirstStyle';s.textContent=`#payList .row{position:relative}#payList .payroll-gross-hero{padding:12px 0 8px;border:0}#payList .payroll-gross-value{font-size:2rem;line-height:1.08;color:var(--ink);font-weight:850;letter-spacing:-.04em}#payList .payroll-tax-label{font-size:.72rem;color:var(--text-muted);font-weight:500;margin-left:4px}#payList .payroll-support{font-size:1rem;line-height:1.4;color:var(--text-muted);font-weight:500;margin-top:2px}#payList .payroll-has-issue{border-color:var(--warning)!important}#payList .payroll-contract-note{font-size:.78rem!important;color:var(--warning)!important;font-weight:650!important}#payList .contract-source-badge{display:none!important}#payList .kpi-row .kpi-label,#payList .payroll-total-net{display:none!important}#payList .kpi-row .kpi-value{font-size:3rem!important;font-weight:900!important;color:var(--ink)!important;letter-spacing:-.05em}#payList .kpi-row .kpi-value::after{content:' (세전)';font-size:.8rem;font-weight:500;color:var(--text-muted);letter-spacing:0}`;document.head.appendChild(s)}
  function compactSupport(rec){return `${typeof fmtHM==='function'?fmtHM(rec.sec):''} 근무`}
  function annotatePayroll(){installStyle();const box=document.getElementById('payList');if(!box||!lastResult)return;const rows=[...box.children].filter(x=>x.classList?.contains('row')).slice(0,lastResult.rows.length);rows.forEach((card,i)=>{const rec=lastResult.rows[i];if(!rec)return;card.dataset.employeeId=String(rec.employee_id);card.querySelectorAll('.payroll-gross-hero,.payroll-contract-summary,.payroll-contract-note').forEach(n=>n.remove());const edit=card.querySelector('[data-edit]');if(edit){if(rec.contractMode==='MISSING_CONTRACT'){edit.textContent='계약 등록';edit.onclick=()=>{location.href=`employment_contracts.html?employee=${rec.employee_id}&from=admin`}}else edit.remove()}const head=card.querySelector('.nm');const issueBadge=head?.querySelector('.badge.issue');if(issueBadge)issueBadge.remove();card.classList.toggle('payroll-has-issue',!!rec.issues||!!rec.contractIssue);head?.querySelector('.contract-source-badge')?.remove();const detail=card.children[1];if(detail){detail.className='payroll-support';detail.innerHTML=compactSupport(rec)}if(rec.pay){const hero=document.createElement('div');hero.className='payroll-gross-hero';hero.innerHTML=`<strong class="payroll-gross-value">${Number(rec.pay.gross||0).toLocaleString()}원</strong><span class="payroll-tax-label">(세전)</span>`;card.children[0]?.after(hero)}if(rec.contractIssue&&!rec.pay){const n=document.createElement('div');n.className='payroll-contract-note';n.textContent='급여 확인 필요';card.appendChild(n)}});document.getElementById('payrollContractSourceNote')?.remove();document.getElementById('payrollCloseBlockNote')?.remove();const blockers=(lastResult.rows||[]).filter(r=>!['CONTRACT','MONTHLY'].includes(r.contractMode)||Number(r.issues||0)>0);const close=document.getElementById('btnClose');if(close){close.disabled=!!blockers.length;close.title=blockers.length?'확인필요 항목을 먼저 해결하세요.':''}}

  drawPay=async function(ym){cache.clear();await baseDrawPay(ym);annotatePayroll()};
  openMonthAdjust=function(emp,ym,ov){baseOpenMonthAdjust(emp,ym,ov);const modal=document.getElementById('addVeil')?.querySelector('.modal');if(!modal)return;['maWage','maJh','maTax'].forEach(id=>{const f=document.getElementById(id)?.closest('.field');if(f)f.style.display='none'});const title=modal.querySelector('h3');if(title){const n=document.createElement('div');n.style.cssText='font-size:.78rem;color:var(--text-muted);margin:-8px 0 12px';n.textContent='시급·주휴시간·세율은 계약조건에서 가져옵니다.';title.after(n)}};
  if(document.getElementById('payList')){const m=document.getElementById('payMonth');if(m)drawPay(m.value)}

  // Recompute in memory, then patch only volatile values. Existing cards never disappear.
  const patchLive=async()=>{const box=document.getElementById('payList'),m=document.getElementById('payMonth');if(!box||!m||document.visibilityState!=='visible'||refreshBusy)return;if(document.getElementById('addVeil')?.classList.contains('show'))return;refreshBusy=true;try{const R=await computeMonthPayroll(m.value);for(const rec of R.rows||[]){const card=box.querySelector(`.row[data-employee-id="${rec.employee_id}"]`);if(!card)continue;const detail=card.querySelector('.payroll-support');if(detail)detail.innerHTML=compactSupport(rec);const gross=card.querySelector('.payroll-gross-value');if(gross&&rec.pay)gross.textContent=`${Number(rec.pay.gross||0).toLocaleString()}원`;let night=card.querySelector('.payroll-night-note');if(rec.pay?.night){if(!night){night=document.createElement('div');night.className='payroll-night-note';night.style.cssText='font-size:.7rem;color:var(--text-muted);margin-top:3px';const host=card.querySelector('.payroll-card-body')||card;host.appendChild(night)}night.textContent=`야간 ${Number(rec.pay.nightHours||0).toFixed(2)}시간 · 야간수당 ${Number(rec.pay.night||0).toLocaleString()}원`}else night?.remove()}const kpi=box.querySelector('.kpi-row');if(kpi){const label=kpi.querySelector('.kpi-label'),value=kpi.querySelector('.kpi-value');if(label)label.textContent='';if(value)value.textContent=`${Number(R.totalGross||0).toLocaleString()}원`;kpi.querySelector('.payroll-total-net')?.remove()}}catch(e){console.warn('[payroll live patch]',e)}finally{refreshBusy=false}};
  window.__patchPayrollLiveValues=patchLive;
  setInterval(patchLive,10000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')patchLive()});
})();
