import fs from 'node:fs';
import assert from 'node:assert/strict';
const js=fs.readFileSync('actual_attendance.js','utf8');
const css=fs.readFileSync('actual_attendance.css','utf8');
const html=fs.readFileSync('actual_attendance.html','utf8');
const a=js.indexOf('function renderMonth(){'),b=js.indexOf('function toAxisHour',a),m=js.slice(a,b);
assert(m.includes('class="lines"'),'monthly calendar must show employee names');
assert(m.includes('calendar-normal'),'completed-work dot required');
assert(m.includes('calendar-working'),'working dot required');
assert(m.includes('calendar-issue'),'issue dot required');
assert(m.includes('근무 완료')&&m.includes('근무 중')&&m.includes('확인 필요'),'three-state legend required');
assert(css.includes('.calendar-normal,.legend .dot.normal'),'green completed style required');
assert(css.includes('.calendar-working,.legend .dot.working'),'blue working style required');
assert(css.includes('.calendar-issue,.legend .dot.issue'),'brown issue style required');
assert(html.includes('‹ 뒤로'),'back button label required');
assert(html.includes('actual_attendance.css?v=20260924b'));
assert(html.includes('actual_attendance.js?v=20260924b'));
new Function(js);
console.log('actual attendance monthly detail QA: PASS');
