import fs from 'node:fs';
let pass=0,fail=0;const ok=(n,c)=>{if(c){pass++;console.log('✓ '+n)}else{fail++;console.error('✗ '+n)}};
const index=fs.readFileSync('index.html','utf8');
const guard=fs.readFileSync('monthly_schedule_contract_guard.js','utf8');
const css=fs.readFileSync('monthly_schedule_contract_guard.css','utf8');
ok('admin uses current subnav IA',index.includes('admin-subtabs')&&index.includes('직원 관리')&&index.includes('급여')&&index.includes('운영시간'));
ok('contract document duplicate quick action removed',!index.includes('id="quickDocs"')&&!index.includes('document.getElementById("quickDocs")'));
ok('attendance is promoted to the top-level navigation',index.includes('id="tabAttendance" href="#attendance"'));
ok('hourly contract weekdays have explicit calendar marker predicate',guard.includes('function isContractWorkday')&&guard.includes("b.classList.toggle('contract-day',isContractWorkday"));
ok('monthly contracts are not mislabeled as weekday contracts',guard.includes("if(!c||c.payroll_type!=='HOURLY')return null"));
ok('contract-day marker is visually distinct from saved schedule state',css.includes(".calday.contract-day:before{content:'계약'"));
ok('mobile successful save skips redundant completion screen',guard.includes('if(mobile()&&S.saved){S.saved=false;S.step=3;S.selected.clear()}'));
ok('contract guide remains informational and exceptions remain allowed',guard.includes('대타·추가근무 일정으로 등록할 수 있습니다')&&!guard.includes('return false'));
console.log(`\nAdmin/monthly UX cleanup QA: ${pass} passed, ${fail} failed`);if(fail)process.exit(1);
