import fs from 'node:fs';import assert from 'node:assert/strict';
const html=fs.readFileSync('employment_contracts.html','utf8');
const js=fs.readFileSync('employment_contract_docs_v1.js','utf8');
let pass=0;const t=(n,f)=>{f();pass++;console.log('PASS',n)};
t('contract doc integration loads after atomic/payroll bridge and before form-state wrapper',()=>{const a=html.indexOf('employment_period_atomic_v1.js'),b=html.indexOf('employment_contract_payroll_bridge_v1.js'),d=html.indexOf('employment_contract_docs_v1.js'),s=html.indexOf('employment_contract_form_state_fix.js');assert(a>0&&b>a&&d>b&&s>d)});
t('documents are queried by employee + selected contract',()=>{assert(js.includes("admin_contract_doc_list"));assert(js.includes('p_contract_id:contractId'));assert(js.includes('loadDocPanels(c)'))});
t('contract form contains contract document section before save',()=>{assert(js.includes('근로계약서'));assert(js.includes('contract-doc-area contract-doc-inline'));assert(js.includes('mainCard=function'));assert(js.includes('html.replace(save,`${formPanel(c)}${save}`)'))});
t('new contract can stage a document before contract id exists',()=>{assert(js.includes('S.pendingContractFile'));assert(js.includes('계약 저장 시 함께 첨부됩니다.'));assert(js.includes("c?.id??'new'"))});
t('staged document is linked to newly saved contract id',()=>{assert(js.includes('BE.contractSet=async function(args)'));assert(js.includes('BE.contractDocAdd(S.employeeId,Number(r.id),path,file)'));assert(js.includes('p_contract_id:contractId'))});
t('legacy employee-only documents remain visible as unclassified and are never auto-assigned',()=>{assert(js.includes('admin_unclassified_doc_list'));assert(js.includes('연결되지 않은 계약서'));assert(!js.includes('UPDATE employee_documents'));assert(!js.includes('assignContract'))});
t('upload validates supported file types and 10MB limit',()=>{assert(js.includes("'application/pdf','image/jpeg','image/png'"));assert(js.includes('file.size>10485760'))});
t('document upload failure does not falsely roll back an already saved contract',()=>{assert(js.includes('계약은 저장됐지만 계약서 첨부에 실패했습니다.'));assert(js.includes('return r;'))});
t('current server delete restriction remains surfaced until DB policy is changed',()=>{assert(js.includes("TOO_OLD_TO_DELETE"));assert(js.includes("NOT_OWN_UPLOAD"));assert(js.includes("admin_doc_delete"))});
console.log(`Contract docs V2 QA: ${pass} PASS`);
