import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const context={window:{}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('operations_reference_v208.js','utf8'),context);
const ref=context.window.OPERATIONS_REFERENCE_V208;
const html=fs.readFileSync('index.html','utf8');
const ui=fs.readFileSync('operations_reference_ui_v208.js','utf8');
const css=fs.readFileSync('operations_v1.css','utf8');
const testMode=fs.readFileSync('test_mode_ui_v1.js','utf8');
const payrollLoader=fs.readFileSync('payroll_elapsed_weeks_v1.js','utf8');
const removalMigration=fs.readFileSync('provenance/source-migrations/20260927142500_hq_product_removal_scheduling.sql','utf8');
const pendingMigration=fs.readFileSync('provenance/source-migrations/20260927145530_hq_product_pending_changes.sql','utf8');
const updateScheduleMigration=fs.readFileSync('provenance/source-migrations/20260927155000_hq_product_update_scheduling.sql','utf8');

assert.equal(ref.version,'v208');
assert.equal(ref.inventory.length,172,'all non-heading inventory rows must be retained');
assert.equal(ref.recipes.length,125,'all beverage, food, and batch recipe rows must be retained');
assert.equal(ref.shelf_life.length,125,'the shelf-life reference table must be retained');

const can500=ref.inventory.find(x=>x.name==='500 캔');
assert.deepEqual([can500.minimum_text,can500.current_text,can500.order_text],['야창 2b','매장 1봉/ 야창 2b','창고 여분 보면서']);
const americano=ref.recipes.find(x=>x.menu_name==='아메리카노');
assert.equal(americano.variants.length,3);
assert.match(americano.variants.find(x=>x.label==='HOT(13oz)').content,/온수 225g/);
assert.match(americano.variants.find(x=>x.label==='ICED(1L)').content,/에스프레소4샷/);
const hotdog=ref.recipes.find(x=>x.menu_name==='치즈 치폴레 핫도그');
assert.equal(hotdog.source_version,'26.09.11');
assert.match(hotdog.variants[0].content,/눈꽃 치즈 50g/);
const milkLife=ref.shelf_life.find(x=>x.name==='우유');
assert.equal(milkLife.expiry_after,'3일');

const dataAt=html.indexOf('operations_reference_v208.js?v=20260927v220');
const appAt=html.indexOf('operations_v1.js?v=20260927v223');
const uiAt=html.indexOf('operations_reference_ui_v208.js?v=20260927v223');
assert.ok(dataAt>=0&&dataAt<appAt&&appAt<uiAt,'reference data, legacy operations, then reference UI must load in order');
assert.ok(html.includes('const APP_VERSION="v0.01"'));
assert.ok(ui.includes('HOT(13oz)')===false,'variant labels must come from source data, not hardcoded UI');
assert.ok(ui.includes('발주 필요 품목과 인하대점 재고 기준'));
assert.ok(ui.includes('공식 제조 기준과 직접 등록한 레시피'));
assert.ok(!ui.includes('admin-subtabs'),'reference renderer must not copy the admin tab bar');
assert.ok(!ui.includes('원본 재고'),'inventory summary switcher must not be rendered');
assert.ok(!ui.includes('공식 레시피'),'recipe summary switcher must not be rendered');
assert.ok(ui.includes('발주 필요'),'inventory order recommendations must be present');
assert.ok(ui.includes('ops-order-bars'),'inventory order graph must be present');
assert.ok(ui.includes('BE.inventoryManualSave'),'inventory create and edit must save through the management API');
assert.ok(ui.includes('+ 레시피 등록'),'recipe registration must be available on the main screen');
assert.ok(ui.includes('BE.recipeSave'),'recipe create and edit must save through the management API');
assert.ok(!ui.includes('originalRender("inventory")'),'inventory management must not switch to a second screen');
assert.ok(!ui.includes('originalRender("recipe")'),'recipe management must not switch to a second screen');
assert.ok(!ui.includes('9레시피 패널'),'source labels must not appear on recipe cards');
assert.ok(!ui.includes('10레시피 패널'),'source labels must not appear in recipe details');
assert.ok(ui.includes('ops-recipe-static'),'registered recipe cards must have a single edit entry point');
assert.ok(ui.includes('window.openHqProductModal'),'HQ product rollout must open as a modal');
assert.ok(ui.includes('+ 신제품 등록')&&ui.includes('− 제품 삭제'),'HQ modal must expose product add and remove actions');
assert.ok(ui.includes('ops-hq-inventory-picker'),'new products must select recipe ingredients from inventory');
assert.ok(ui.includes('기존 카테고리')&&ui.includes('새 카테고리 생성'),'product editor must support existing and new categories');
assert.ok(ui.includes('hqLaunchDate')&&ui.includes('BE.hqProductSchedule'),'product editor must support scheduled rollout dates');
assert.ok(ui.includes('BE.hqProductRemovalSchedule')&&ui.includes('삭제 예약'),'selected products must support scheduled removal');
assert.ok(ui.includes('hqSelectAll')&&ui.includes('hqRemovalCategory')&&ui.includes('hqRemovalSort'),'product removal must support bulk selection, category filtering, and sorting');
assert.ok(ui.includes('전체 선택')&&ui.includes('hqSelectionStatus')&&ui.includes('개 선택 중'),'bulk selection count must appear beside the select-all label');
assert.ok(!ui.includes('ops-hq-link-stats')&&!ui.includes('30일 매출')&&!ui.includes('30일 매입'),'product cards must omit rollout and 30-day transaction stats');
assert.ok(ui.includes('thumbnail_url')&&ui.includes('ops-hq-thumb'),'product cards must display thumbnails');
assert.ok(ui.includes('originalQuantity')&&ui.includes('ops-hq-current-qty')&&ui.includes('수정값'),'product editor must show current ingredient quantity beside an editable value');
assert.ok(ui.includes('has_pending_changes')&&ui.includes('아직 배포하지 않은 변경사항이 없습니다.'),'all-store apply must only enable for unapplied edits');
assert.ok(ui.includes("pending?' is-pending':'')")&&css.includes('.ops-hq-apply.is-pending')&&css.includes('color:#fff!important'),'pending all-store apply must be a green button with white text');
assert.ok(ui.includes('recipeThumbnail')&&ui.includes('ops-reference-recipe-content'),'branch recipe cards must render thumbnails');
assert.ok(ui.includes('수정 적용 예약일')&&ui.includes('수정 예약')&&ui.includes('updateScheduled'),'active product edits must support scheduled all-store application');
assert.ok(ui.includes('기존 재고품목 선택')&&ui.includes('신규 품목 등록')&&ui.includes('unifiedInventoryCatalog'),'branch inventory registration must select existing catalog items or create a new item');
assert.ok(ui.includes('dragstart')&&ui.includes('preventDefault'),'product editor content dragging must be blocked');
assert.ok(html.includes('hq-title-row')&&html.includes('hq-product-button'),'product rollout button must share the dashboard title row');
assert.ok(css.includes('.ops-hq-removal-controls')&&css.includes('.ops-hq-card-check'),'removal selection controls must be styled');
assert.ok(testMode.includes('#testModeControls{position:fixed;z-index:10020;left:max(8px,env(safe-area-inset-left))'),'test controls must be pinned to the safe top-left corner');
assert.ok(html.includes('payroll_elapsed_weeks_v1.js?v=20260927v221'),'employee number loader must be cache-busted');
assert.ok(payrollLoader.includes('test_mode_ui_v1.js?v=20260927v221'),'top-left test controls must bypass stale browser cache');
assert.ok(removalMigration.includes('admin_hq_product_removal_schedule')&&removalMigration.includes("'DISCONTINUE'::text"),'database must schedule and execute due removals');
assert.ok(pendingMigration.includes('has_pending_changes')&&pendingMigration.includes('track_hq_product_pending_changes'),'database must persist and clear unapplied product edits');
assert.ok(updateScheduleMigration.includes("status='ACTIVE' and has_pending_changes")&&updateScheduleMigration.includes("'schedule_type','UPDATE'"),'database cron must apply scheduled active-product edits');
assert.ok(ui.includes('cleanExample'),'legacy example prefixes must be stripped from displayed data');
assert.ok(!ui.includes('tab==="products"'),'HQ rollout must not render as an admin tab');
console.log('operations reference v219 QA PASS');
