/* Store controls V1: admin-configured open/close time + automatic correction-based forced checkout. */
(()=>{
  if(window.__franchiseStoreControlsV1)return;window.__franchiseStoreControlsV1=true;if(typeof BE==='undefined'||typeof renderAdmin!=='function')return;
  const TEST_KEY='franchise_test_mode_v1',inTest=()=>{try{return !!JSON.parse(localStorage.getItem(TEST_KEY)||'null')?.enabled}catch(_){return false}};
  // Store settings RPCs are exposed by the main backend adapter. This overlay must not depend on its private rpc() closure.
  const p=n=>String(n).padStart(2,'0'),fmt=m=>`${Math.floor(Number(m||0)/60)}:${p(Number(m||0)%60)}`;
  const parseOpen=(h,m)=>{h=Number(h);m=Number(m);if(!Number.isInteger(h)||!Number.isInteger(m)||h<0||h>23||m<0||m>59)return null;return h*60+m};
  const parseClose=(h,m)=>{h=Number(h);m=Number(m);if(!Number.isInteger(h)||!Number.isInteger(m)||h<0||h>47||m<0||m>59)return null;return h*60+m};
  function style(){if(document.getElementById('storeControlsV1Style'))return;const s=document.createElement('style');s.id='storeControlsV1Style';s.textContent=`.store-settings-card{box-sizing:border-box;width:auto;max-width:calc(100% - 24px);margin:12px 12px 14px;padding:14px;border:1px solid var(--line);border-radius:14px;background:var(--panel)}.store-settings-card h3{margin:0 0 10px;font-size:.95rem}.store-settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.store-settings-card label{display:block;font-size:.72rem;color:var(--text-muted);margin:0 0 5px;line-height:1.25;min-height:1.8em}.store-hours-field{min-width:0;display:flex;flex-direction:column}.store-hours-field label{display:flex;align-items:flex-end}.store-settings-card input{width:100%;height:44px;border:1px solid var(--line);border-radius:10px;background:var(--panel2);color:var(--ink);padding:0 10px;box-sizing:border-box}.store-time-pair{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:5px;align-items:center}.store-time-pair span{text-align:center;color:var(--text-muted);font-weight:700}.store-time-pair input{text-align:center;min-width:0}.store-close-hint{font-size:.7rem;color:var(--text-muted);margin-top:8px;line-height:1.45}.store-force-status{font-size:.72rem;color:var(--text-muted);margin-top:8px;min-height:1.1em}`;document.head.appendChild(s)}
  async function renderStoreHours(){style();view.innerHTML='<div class="store-hours-page"><div class="section-t">운영시간</div><div id="storeHoursMount"></div></div>';const host=document.getElementById('storeHoursMount'),card=document.createElement('section');card.id='storeSettingsCard';card.className='store-settings-card';card.innerHTML=`<h3>매장 운영시간</h3><div class="store-settings-grid"><div class="store-hours-field"><label>오픈 시간</label><div class="store-time-pair"><input id="storeOpenH" inputmode="numeric" pattern="[0-9]*" placeholder="07"><span>:</span><input id="storeOpenM" inputmode="numeric" pattern="[0-9]*" placeholder="00"></div></div><div class="store-hours-field"><label>마감 시간 <small style="margin-left:4px;font-weight:400">(24시 이후 가능)</small></label><div class="store-time-pair"><input id="storeCloseH" inputmode="numeric" pattern="[0-9]*" placeholder="25"><span>:</span><input id="storeCloseM" inputmode="numeric" pattern="[0-9]*" placeholder="00"></div></div><div style="grid-column:1/-1"><button class="btn btn-primary btn-block" id="storeSave">저장</button></div></div><div class="store-close-hint" id="storeCutoffHint"></div><div class="store-force-status" id="storeForceStatus"></div>`;host.appendChild(card);try{const x=await BE.storeSettingsGet();storeOpenH.value=p(Math.floor(x.open_minute/60));storeOpenM.value=p(x.open_minute%60);storeCloseH.value=Math.floor(x.close_minute/60);storeCloseM.value=p(x.close_minute%60);void 0}catch(e){console.warn('[store-hours-load]',e)}const updateHint=()=>{const x=parseClose(storeCloseH.value,storeCloseM.value);storeCutoffHint.innerHTML=x==null?'마감 시간을 확인하세요.':`<div>마감 시간이 되면 아직 근무 중인 직원은 자동으로 퇴근 처리됩니다. <b>현재 기준 ${fmt(x)}</b></div><div style="margin-top:4px">24시를 넘는 시간은 다음 날로 계산합니다. 예: 25:00 = 다음 날 새벽 1:00</div>`};['storeCloseH','storeCloseM'].forEach(id=>document.getElementById(id).addEventListener('input',updateHint));updateHint();storeSave.onclick=async()=>{if(inTest()){toast('err','테스트 모드','운영시간은 변경하지 않습니다.');return}const o=parseOpen(storeOpenH.value,storeOpenM.value),x=parseClose(storeCloseH.value,storeCloseM.value);if(o==null||x==null||x<=o){toast('err','입력 확인','오픈·마감 시간을 확인하세요.');return}try{const r=await BE.storeSettingsSet(o,x);if(r?.ok){toast('in','운영시간 저장됨',`${fmt(o)} ~ ${fmt(x)}`);await enforce(true)}else toast('err','저장 실패',r?.error||'')}catch(e){toast('err','저장 실패',e.message)}}}
  window.renderStoreHours=renderStoreHours;
  let busy=false;async function enforce(show=false){if(!LIVE||inTest()||busy)return;busy=true;try{const r=await BE.enforceStoreClose();if(show||Number(r?.closed)>0){const el=document.getElementById('storeForceStatus');if(el)el.textContent=Number(r?.closed)>0?`자동 강제퇴근 ${r.closed}명 반영됨`:`현재 강제퇴근 대상 없음`;if(Number(r?.closed)>0){toast('out','마감 자동퇴근',`${r.closed}명 반영`);if(location.hash==='#admin')setTimeout(()=>renderAdmin(),100)}}}catch(e){console.warn('[store-close]',e)}finally{busy=false}}
  // Automatic store close is enforced server-side by pg_cron. The browser only performs an authenticated one-shot check immediately after an admin changes store hours.

})();