-- v0.21: supplied inventory workbook + supplied recipe PDFs are authoritative source data.
alter table public.inventory_items add column if not exists category text, add column if not exists source_unit_system text, add column if not exists source_minimum_text text, add column if not exists source_current_text text, add column if not exists source_order_text text, add column if not exists source_note text;
with v(sku,category,unit_system,minimum_text,current_text,order_text,note) as (values
($q$SRC-E50BB6695B90$q$,$q$포장$q$,$q$박스(b)/봉$q$,$q$야창 2b$q$,$q$매장 1봉/ 야창 2b$q$,$q$창고 여분 보면서$q$,$q$$q$),
($q$SRC-42BE5C02F625$q$,$q$포장$q$,$q$박스(b)/봉$q$,$q$야창 1b$q$,$q$매장 1봉 / 야창 1b$q$,$q$일요일 1박스(부족하면$q$,$q$$q$),
($q$SRC-BF74322399D9$q$,$q$포장$q$,$q$박스(b)/봉$q$,$q$야창 1b$q$,$q$매장 3봉 / 야창 1b$q$,$q$일요일 1박스(부족하면$q$,$q$$q$),
($q$SRC-B09D592F0C6B$q$,$q$포장$q$,$q$줄$q$,$q$4-5줄$q$,$q$9줄$q$,$q$1박스$q$,$q$$q$),
($q$SRC-FD44875D4DB3$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$2줄$q$,$q$6줄$q$,$q$1b$q$,$q$$q$),
($q$SRC-310B3A47303B$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$1줄$q$,$q$매장 1.3줄 / 야창 1b$q$,$q$1b$q$,$q$$q$),
($q$SRC-793B0A1F9D2A$q$,$q$포장$q$,$q$봉$q$,$q$1봉$q$,$q$1봉$q$,$q$1봉$q$,$q$$q$),
($q$SRC-5B86A91F7E00$q$,$q$포장$q$,$q$봉$q$,$q$2봉$q$,$q$1봉$q$,$q$2봉$q$,$q$$q$),
($q$SRC-989EC5D6BC3F$q$,$q$포장$q$,$q$봉/개$q$,$q$2개$q$,$q$2봉$q$,$q$1봉$q$,$q$$q$),
($q$SRC-EE04D9010BF8$q$,$q$포장$q$,$q$봉/개$q$,$q$2개$q$,$q$2봉$q$,$q$1개$q$,$q$$q$),
($q$SRC-04A1899E3060$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$절반$q$,$q$매장 1줄 / 야창 1b$q$,$q$1b$q$,$q$플라스틱 컵(오가다용 16온스)$q$),
($q$SRC-B4962814AD15$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$1줄$q$,$q$매장 거의 1b / 야창 -$q$,$q$1b$q$,$q$$q$),
($q$SRC-3842AEC53047$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$4줄$q$,$q$매장 1b / 야창 -$q$,$q$1b$q$,$q$플라스틱 컵(오가다용 32온스)$q$),
($q$SRC-DCA592FA3639$q$,$q$포장$q$,$q$박스(b)$q$,$q$절반 사용$q$,$q$매장 거의1b / 야창 -$q$,$q$1b$q$,$q$백억 돔리드 (오가다용 92파이)$q$),
($q$SRC-8A30083BE565$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$1줄$q$,$q$매장 3.5줄 / 야창 1b$q$,$q$1b$q$,$q$$q$),
($q$SRC-88335B29F123$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$2줄$q$,$q$매장 1b+2줄 / 야창 -$q$,$q$1b$q$,$q$돔리드 (107파이)$q$),
($q$SRC-D93949BA8381$q$,$q$포장$q$,$q$박스(b)$q$,$q$박스 절반 사용$q$,$q$매장 1b+조금 / 야창 -$q$,$q$1b$q$,$q$1리터 홀더 >>> 백억 1리터 홀더 500 홀더 >>> 백억 컵 홀더 (1316 공용) 355 홀더 >>> 백억 캔 홀더$q$),
($q$SRC-019C7CC78CF0$q$,$q$포장$q$,$q$박스(b)$q$,$q$박스 절반 사용$q$,$q$매장 거의1b / 야창 -$q$,$q$1b$q$,$q$$q$),
($q$SRC-A142BE029F0B$q$,$q$포장$q$,$q$박스(b)$q$,$q$박스 절반 사용$q$,$q$매장 절반 / 야창 -$q$,$q$1b$q$,$q$$q$),
($q$SRC-E04FE556DD6C$q$,$q$포장$q$,$q$봉$q$,$q$2봉지$q$,$q$1봉$q$,$q$2봉$q$,$q$$q$),
($q$SRC-29444F5B3A2D$q$,$q$포장$q$,$q$묶음$q$,$q$2묶음$q$,$q$2묶$q$,$q$2묶음$q$,$q$팝콘 봉투임 팝콘 컵이랑 헷갈리지 X$q$),
($q$SRC-7CABA37F9D35$q$,$q$포장$q$,$q$줄$q$,$q$2줄$q$,$q$매장 3줄 / 야창 -$q$,$q$2줄$q$,$q$투명컵7온스$q$),
($q$SRC-06BFE0236EE5$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$박스 절반 사용$q$,$q$매장 2줄 / 야창 6줄$q$,$q$1b$q$,$q$$q$),
($q$SRC-7D31885DAF1C$q$,$q$포장$q$,$q$봉/개$q$,$q$막개봉$q$,$q$2봉+정리함꽉$q$,$q$2개$q$,$q$$q$),
($q$SRC-3B1848FB8721$q$,$q$포장$q$,$q$봉$q$,$q$막개봉$q$,$q$1봉+정리함 1/2$q$,$q$2봉$q$,$q$$q$),
($q$SRC-5FF946220D61$q$,$q$포장$q$,$q$봉$q$,$q$막개봉$q$,$q$1봉+정리함꽉$q$,$q$2봉$q$,$q$$q$),
($q$SRC-2EAD6C0537CA$q$,$q$포장$q$,$q$줄$q$,$q$1줄$q$,$q$1줄$q$,$q$3줄$q$,$q$2온스$q$),
($q$SRC-D12639B321F9$q$,$q$포장$q$,$q$줄$q$,$q$1줄$q$,$q$1줄$q$,$q$2줄$q$,$q$2온스 검색$q$),
($q$SRC-D9BDBD3B7BFA$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$2줄$q$,$q$매장 2줄 / 야창 2줄$q$,$q$1b$q$,$q$(재고없음일욜)$q$),
($q$SRC-5D53F73B8BF4$q$,$q$포장$q$,$q$줄$q$,$q$2줄$q$,$q$매장 1줄 / 야창 6줄$q$,$q$$q$,$q$$q$),
($q$SRC-8C0739BC6ED2$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$2줄$q$,$q$매장 1줄 / 야창 1줄$q$,$q$1b(보통2주간격)$q$,$q$$q$),
($q$SRC-75FB8E5AC032$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$1줄$q$,$q$매장 2줄 / 야창 1b$q$,$q$1b$q$,$q$$q$),
($q$SRC-8AAB7F9AC372$q$,$q$포장$q$,$q$박스(b)$q$,$q$박스 절반 사용$q$,$q$매장 각각 정리함꽉$q$,$q$1b$q$,$q$세트로 옴$q$),
($q$SRC-969B1E0B55E3$q$,$q$포장$q$,$q$줄$q$,$q$2줄$q$,$q$매장 1줄 / 야창 6줄$q$,$q$1박스$q$,$q$내열사각 용기$q$),
($q$SRC-20BBB3EAF284$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$1줄$q$,$q$매장 1줄 / 야창 6줄$q$,$q$1b$q$,$q$//뚜껑$q$),
($q$SRC-2CEF81E4CF9E$q$,$q$포장$q$,$q$박스(b)/줄$q$,$q$2줄$q$,$q$1줄$q$,$q$2b$q$,$q$세트말고 둘다 단품/ 통합검색>샌드>더보기>즐찾$q$),
($q$SRC-53AF30D7477E$q$,$q$포장$q$,$q$박스(b)/봉/줄$q$,$q$파란색 1봉$q$,$q$매장 1줄 / 야창 2줄$q$,$q$1b$q$,$q$용기랑 동일$q$),
($q$SRC-37786147C7A4$q$,$q$포장$q$,$q$박스(b)/개$q$,$q$막개봉$q$,$q$3b$q$,$q$2개$q$,$q$$q$),
($q$SRC-D1B5E726F003$q$,$q$포장$q$,$q$봉$q$,$q$2봉$q$,$q$2봉+정리함꽉$q$,$q$1봉$q$,$q$7*250mm / 6,300$q$),
($q$SRC-28A14C5A24B2$q$,$q$포장$q$,$q$봉/개$q$,$q$절반 사용$q$,$q$1봉+정리함1/5$q$,$q$1개유지$q$,$q$12*250mm / 4,300$q$),
($q$SRC-9970A7D8D313$q$,$q$포장$q$,$q$봉/개$q$,$q$막봉지 개봉$q$,$q$1봉+1$q$,$q$1~2개$q$,$q$$q$),
($q$SRC-89F68F8A135D$q$,$q$포장$q$,$q$봉/묶음$q$,$q$막묶음 개봉$q$,$q$거의1봉$q$,$q$1묶음$q$,$q$$q$),
($q$SRC-BF6B6598CDF3$q$,$q$포장$q$,$q$묶음$q$,$q$막박스 개봉$q$,$q$매장 약3묶 / 야창 -$q$,$q$쿠팡에 요청$q$,$q$마감3시$q$),
($q$SRC-8D2C67C80A33$q$,$q$기타$q$,$q$박스(b)$q$,$q$3b$q$,$q$8b$q$,$q$5B$q$,$q$$q$),
($q$SRC-D691964BFB59$q$,$q$기타$q$,$q$박스(b)/봉/묶음$q$,$q$1봉$q$,$q$1묶$q$,$q$1b$q$,$q$$q$),
($q$SRC-A32CF37F452A$q$,$q$기타$q$,$q$박스(b)$q$,$q$정리함채우면$q$,$q$절반이상$q$,$q$1B$q$,$q$$q$),
($q$SRC-41F71F31F30A$q$,$q$기타$q$,$q$묶음$q$,$q$박스 절반 사용$q$,$q$매장 5묶 / 야창 -$q$,$q$1박스 (쿠팡)$q$,$q$$q$),
($q$SRC-17C7A13B8DC3$q$,$q$기타$q$,$q$봉/개/kg$q$,$q$5kg 통절반$q$,$q$매장 소분통2개 / 야창 1봉(개봉)$q$,$q$1봉지$q$,$q$$q$),
($q$SRC-3224FB7537EE$q$,$q$기타$q$,$q$통$q$,$q$1/3통$q$,$q$거의1통$q$,$q$$q$,$q$$q$),
($q$SRC-90A05715126A$q$,$q$기타$q$,$q$개/통$q$,$q$펌핑 안나오면$q$,$q$절반이하+1통$q$,$q$제일 큰거 1개$q$,$q$$q$),
($q$SRC-37A584808ACD$q$,$q$스티커$q$,$q$묶음$q$,$q$1묶음$q$,$q$많음$q$,$q$4.0$q$,$q$$q$),
($q$SRC-8E81074E7327$q$,$q$스티커$q$,$q$묶음$q$,$q$1묶음$q$,$q$많음$q$,$q$4.0$q$,$q$$q$),
($q$SRC-0EA2E9F6FBA8$q$,$q$스티커$q$,$q$묶음$q$,$q$1묶음$q$,$q$많음$q$,$q$4.0$q$,$q$$q$),
($q$SRC-D07F357B2E64$q$,$q$스티커$q$,$q$묶음$q$,$q$1묶음$q$,$q$많음$q$,$q$4.0$q$,$q$$q$),
($q$SRC-4FBDA98960D0$q$,$q$스티커$q$,$q$줄$q$,$q$반줄$q$,$q$1.5줄$q$,$q$1줄$q$,$q$$q$),
($q$SRC-797AC369D2EB$q$,$q$스티커$q$,$q$박스(b)/묶음$q$,$q$1묶음$q$,$q$많음$q$,$q$1B$q$,$q$$q$),
($q$SRC-D7D35A252DF3$q$,$q$스티커$q$,$q$박스(b)/묶음$q$,$q$1묶음$q$,$q$많음$q$,$q$1B$q$,$q$$q$),
($q$SRC-6848FB596F21$q$,$q$스티커$q$,$q$박스(b)/묶음$q$,$q$1묶음$q$,$q$많음$q$,$q$1B$q$,$q$$q$),
($q$SRC-2BB68F549CED$q$,$q$스티커$q$,$q$원본 기준$q$,$q$$q$,$q$많음$q$,$q$$q$,$q$$q$),
($q$SRC-5899253FE19C$q$,$q$스티커$q$,$q$박스(b)/묶음$q$,$q$1묶음$q$,$q$많음$q$,$q$1B$q$,$q$$q$),
($q$SRC-BC43E975E95A$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$개$q$,$q$거의 다쓰면$q$,$q$절반이상$q$,$q$1개$q$,$q$$q$),
($q$SRC-47C9DBB34AC5$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$$q$,$q$막개봉$q$,$q$$q$,$q$$q$),
($q$SRC-82F9DE16332D$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$$q$,$q$1봉$q$,$q$$q$,$q$$q$),
($q$SRC-05DD00D5674A$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$4-5봉$q$,$q$3봉$q$,$q$10봉 유지$q$,$q$맥스 1개 남거나, 성수기$q$),
($q$SRC-4611418A05BB$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉/개$q$,$q$1봉$q$,$q$2봉$q$,$q$1개$q$,$q$$q$),
($q$SRC-84B0A55BD436$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$2봉$q$,$q$-$q$,$q$1봉$q$,$q$$q$),
($q$SRC-5EB57167DBD0$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$1봉$q$,$q$막개봉$q$,$q$2봉$q$,$q$$q$),
($q$SRC-F59C4B123DFE$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$2봉$q$,$q$1봉$q$,$q$2봉$q$,$q$$q$),
($q$SRC-3F7CE569349E$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉/개$q$,$q$막개봉$q$,$q$1봉$q$,$q$1개$q$,$q$$q$),
($q$SRC-3B720A8B67BD$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$2봉$q$,$q$1봉$q$,$q$2봉$q$,$q$$q$),
($q$SRC-BB4883EAD41B$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$1봉$q$,$q$1봉$q$,$q$2봉$q$,$q$$q$),
($q$SRC-020E3CB86F90$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉/개$q$,$q$막개봉$q$,$q$1봉$q$,$q$1개$q$,$q$$q$),
($q$SRC-3FA2DAEC439B$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$1봉$q$,$q$1봉$q$,$q$3봉$q$,$q$$q$),
($q$SRC-C349B471AAF0$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$개$q$,$q$막개봉$q$,$q$-$q$,$q$1개$q$,$q$$q$),
($q$SRC-96376E31D476$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$$q$,$q$막개봉$q$,$q$$q$,$q$$q$),
($q$SRC-DEFC55E29296$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$1봉$q$,$q$1봉$q$,$q$3봉$q$,$q$$q$),
($q$SRC-3AF5D4D1F813$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$1봉$q$,$q$2봉$q$,$q$3봉$q$,$q$$q$),
($q$SRC-2FF75FD450DB$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$1봉$q$,$q$1봉$q$,$q$2봉$q$,$q$$q$),
($q$SRC-70BEAC62EF71$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$$q$,$q$1봉$q$,$q$$q$,$q$$q$),
($q$SRC-7319FEE3DC35$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$$q$,$q$-$q$,$q$$q$,$q$$q$),
($q$SRC-21068755E307$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$박스(b)/봉$q$,$q$사용중 50퍼일때$q$,$q$매장 거의1봉 / 야창 -$q$,$q$1b$q$,$q$$q$),
($q$SRC-4FF6CAA5BA6B$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$봉$q$,$q$여분 1봉$q$,$q$2봉$q$,$q$금강월드에서 주문$q$,$q$$q$),
($q$SRC-C3ABE712F261$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$개$q$,$q$2개$q$,$q$1병$q$,$q$금강월드에서 주문$q$,$q$$q$),
($q$SRC-616860961D09$q$,$q$파우더 & 티백 & 나쵸 & 팝콘(개봉X,여분만 작성)$q$,$q$박스(b)/봉$q$,$q$5봉$q$,$q$정리함꽉+4봉$q$,$q$1b$q$,$q$$q$),
($q$SRC-8CDBDFFD1564$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$통$q$,$q$3병$q$,$q$3병$q$,$q$3통$q$,$q$$q$),
($q$SRC-D9C675DD02DF$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$통$q$,$q$3별$q$,$q$2병$q$,$q$2통$q$,$q$$q$),
($q$SRC-7AFF92F97B02$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$통$q$,$q$막개봉$q$,$q$1병$q$,$q$1통$q$,$q$$q$),
($q$SRC-BAAC6C06306E$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$막개봉$q$,$q$1병$q$,$q$1개$q$,$q$$q$),
($q$SRC-35273BEFF24A$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$$q$,$q$1병$q$,$q$$q$,$q$$q$),
($q$SRC-8E2785808572$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$막개봉$q$,$q$1병$q$,$q$1개$q$,$q$$q$),
($q$SRC-7085C8E46114$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$1병$q$,$q$1병$q$,$q$$q$,$q$$q$),
($q$SRC-4915AD75336B$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$2병$q$,$q$1병$q$,$q$1개$q$,$q$$q$),
($q$SRC-130C6A28B431$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$막개봉$q$,$q$-$q$,$q$1개$q$,$q$$q$),
($q$SRC-BA6B317FF9D8$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$막개봉$q$,$q$1병$q$,$q$$q$,$q$$q$),
($q$SRC-3C295D07528E$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$막개봉$q$,$q$-$q$,$q$1개$q$,$q$$q$),
($q$SRC-8711EEF1DB3E$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$1병$q$,$q$1병$q$,$q$2개$q$,$q$4개가 안전$q$),
($q$SRC-48EBD82C89BF$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$막개봉$q$,$q$1병$q$,$q$1개$q$,$q$$q$),
($q$SRC-38F242861759$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$$q$,$q$1병$q$,$q$$q$,$q$$q$),
($q$SRC-62E1659D8C60$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$$q$,$q$막개봉 / 2병$q$,$q$$q$,$q$$q$),
($q$SRC-74F023F5F833$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$1병$q$,$q$-$q$,$q$1개$q$,$q$$q$),
($q$SRC-46B79901B77A$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$통$q$,$q$1병$q$,$q$1병$q$,$q$1통$q$,$q$$q$),
($q$SRC-479CECF06C45$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$막개봉$q$,$q$-$q$,$q$1개$q$,$q$$q$),
($q$SRC-70B5EA488C8B$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$막개봉$q$,$q$1병$q$,$q$1개$q$,$q$$q$),
($q$SRC-CC38061189AE$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$개$q$,$q$1병$q$,$q$2병$q$,$q$2개$q$,$q$$q$),
($q$SRC-AC4EF158B3B0$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$$q$,$q$1병$q$,$q$$q$,$q$$q$),
($q$SRC-E0C1B66B5EAA$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$통$q$,$q$1병$q$,$q$1병$q$,$q$1통$q$,$q$$q$),
($q$SRC-5B22EEB0A52D$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$통$q$,$q$막개봉$q$,$q$1병$q$,$q$1통$q$,$q$$q$),
($q$SRC-654817441A39$q$,$q$시럽 & 베이스(개봉X,여분만 작성)$q$,$q$원본 기준$q$,$q$$q$,$q$1병$q$,$q$$q$,$q$$q$),
($q$SRC-693C48560E51$q$,$q$냉동(+1은 개봉된거)$q$,$q$박스(b)/개$q$,$q$5-6개$q$,$q$초코14 / 우유7 / 앙버터4 / 황치즈7$q$,$q$1b$q$,$q$$q$),
($q$SRC-C09B466DC070$q$,$q$냉동(+1은 개봉된거)$q$,$q$봉$q$,$q$1봉지$q$,$q$0+1$q$,$q$1봉$q$,$q$$q$),
($q$SRC-818BA6035E19$q$,$q$냉동(+1은 개봉된거)$q$,$q$개$q$,$q$3개$q$,$q$김치7 / 대패7+여분3$q$,$q$3-4개$q$,$q$$q$),
($q$SRC-6D3EC25EDDE3$q$,$q$냉동(+1은 개봉된거)$q$,$q$줄$q$,$q$1줄$q$,$q$블루베리 1+1 / 어니언 1+1$q$,$q$1줄$q$,$q$$q$),
($q$SRC-798F8BF341F5$q$,$q$냉동(+1은 개봉된거)$q$,$q$봉$q$,$q$1봉$q$,$q$1+1$q$,$q$2봉$q$,$q$$q$),
($q$SRC-91D064FE2597$q$,$q$냉동(+1은 개봉된거)$q$,$q$봉$q$,$q$2봉$q$,$q$1+1$q$,$q$3봉$q$,$q$한입 떡튀김 검색$q$),
($q$SRC-FFC606ABEF55$q$,$q$냉동(+1은 개봉된거)$q$,$q$박스(b)$q$,$q$박스 막개봉$q$,$q$1b$q$,$q$1b$q$,$q$1b씩$q$),
($q$SRC-94FFE5F39075$q$,$q$냉동(+1은 개봉된거)$q$,$q$박스(b)$q$,$q$박스 막개봉$q$,$q$-$q$,$q$1b$q$,$q$오리지널 번 검색$q$),
($q$SRC-9F60A0A64966$q$,$q$냉동(+1은 개봉된거)$q$,$q$개$q$,$q$4개$q$,$q$우유8 / 초코1$q$,$q$3개$q$,$q$$q$),
($q$SRC-E0143FD811CB$q$,$q$냉동(+1은 개봉된거)$q$,$q$원본 기준$q$,$q$1박스$q$,$q$티라미수3 / 더블치즈6$q$,$q$1박$q$,$q$$q$),
($q$SRC-E8A20020B948$q$,$q$냉동(+1은 개봉된거)$q$,$q$개$q$,$q$$q$,$q$9개$q$,$q$$q$,$q$$q$),
($q$SRC-2516D079D6C4$q$,$q$냉동(+1은 개봉된거)$q$,$q$박스(b)/개$q$,$q$막박스 소분$q$,$q$초코 1b+정리함2/3 / 밀크 1b+5개$q$,$q$1b$q$,$q$$q$),
($q$SRC-38214DDA9255$q$,$q$냉동(+1은 개봉된거)$q$,$q$원본 기준$q$,$q$$q$,$q$정리함꽉$q$,$q$$q$,$q$$q$),
($q$SRC-83468C1F1BDB$q$,$q$냉동(+1은 개봉된거)$q$,$q$원본 기준$q$,$q$$q$,$q$-$q$,$q$$q$,$q$$q$),
($q$SRC-71923C7188D6$q$,$q$냉동(+1은 개봉된거)$q$,$q$박스(b)/봉$q$,$q$1봉$q$,$q$6봉$q$,$q$1~2b$q$,$q$$q$),
($q$SRC-0D1197B75AF4$q$,$q$냉동(+1은 개봉된거)$q$,$q$원본 기준$q$,$q$$q$,$q$0+1$q$,$q$$q$,$q$$q$),
($q$SRC-9D926CDF7952$q$,$q$냉동(+1은 개봉된거)$q$,$q$봉/개$q$,$q$$q$,$q$6봉+1개$q$,$q$$q$,$q$$q$),
($q$SRC-A6A9B8AA923F$q$,$q$냉동(+1은 개봉된거)$q$,$q$봉$q$,$q$$q$,$q$12봉$q$,$q$$q$,$q$$q$),
($q$SRC-0FE80C1C2C3F$q$,$q$냉동(+1은 개봉된거)$q$,$q$봉$q$,$q$$q$,$q$8봉$q$,$q$$q$,$q$$q$),
($q$SRC-03503C19DD89$q$,$q$냉동(+1은 개봉된거)$q$,$q$봉/개$q$,$q$1봉$q$,$q$2+1$q$,$q$1개$q$,$q$$q$),
($q$SRC-47BE699CF0F8$q$,$q$냉동(+1은 개봉된거)$q$,$q$봉$q$,$q$1봉$q$,$q$1+1$q$,$q$2봉$q$,$q$$q$),
($q$SRC-92239A789D2E$q$,$q$냉동(+1은 개봉된거)$q$,$q$원본 기준$q$,$q$절반$q$,$q$1+1$q$,$q$$q$,$q$$q$),
($q$SRC-9AA689813080$q$,$q$냉동(+1은 개봉된거)$q$,$q$원본 기준$q$,$q$$q$,$q$1+1$q$,$q$$q$,$q$$q$),
($q$SRC-FE05EC98C29C$q$,$q$냉동(+1은 개봉된거)$q$,$q$원본 기준$q$,$q$$q$,$q$1+1$q$,$q$$q$,$q$$q$),
($q$SRC-15D4C2A578E6$q$,$q$냉장 & 실온$q$,$q$개$q$,$q$냉동 4개$q$,$q$냉장 2 / 냉동 5$q$,$q$4개$q$,$q$8개유지$q$),
($q$SRC-96464EF33C4B$q$,$q$냉장 & 실온$q$,$q$개$q$,$q$냉동6-7개$q$,$q$냉장 4 / 냉동 7$q$,$q$냉동에 16개 맞추기$q$,$q$$q$),
($q$SRC-A823D43F2D66$q$,$q$냉장 & 실온$q$,$q$박스(b)/개$q$,$q$냉동 5-6개$q$,$q$냉장 5 / 냉동 5$q$,$q$1-2b$q$,$q$$q$),
($q$SRC-106DBDE90DDA$q$,$q$냉장 & 실온$q$,$q$박스(b)$q$,$q$30퍼 남았을때$q$,$q$절반이하$q$,$q$1b$q$,$q$$q$),
($q$SRC-EB3AA806D3BF$q$,$q$냉장 & 실온$q$,$q$개$q$,$q$박스 막개봉$q$,$q$2개$q$,$q$1개$q$,$q$$q$),
($q$SRC-2B40FA547D86$q$,$q$냉장 & 실온$q$,$q$원본 기준$q$,$q$$q$,$q$1+1 / 1+1$q$,$q$$q$,$q$$q$),
($q$SRC-594B335C4F68$q$,$q$냉장 & 실온$q$,$q$개/통$q$,$q$1개$q$,$q$0+1$q$,$q$1통$q$,$q$$q$),
($q$SRC-34BA6CCBD65F$q$,$q$냉장 & 실온$q$,$q$개$q$,$q$1개$q$,$q$2+1$q$,$q$1+1$q$,$q$$q$),
($q$SRC-3023E58BD080$q$,$q$냉장 & 실온$q$,$q$개$q$,$q$2개$q$,$q$2+1$q$,$q$2개$q$,$q$$q$),
($q$SRC-B69E5B6EB0F4$q$,$q$냉장 & 실온$q$,$q$원본 기준$q$,$q$$q$,$q$1+1$q$,$q$$q$,$q$$q$),
($q$SRC-91B77EC795E2$q$,$q$냉장 & 실온$q$,$q$개$q$,$q$1개$q$,$q$1+1$q$,$q$1개$q$,$q$여름-막개봉 다쓰고 1개주문(여름 냉동,겨울 해냉)$q$),
($q$SRC-AE44523859F6$q$,$q$냉장 & 실온$q$,$q$개$q$,$q$막개봉$q$,$q$1+1$q$,$q$1개$q$,$q$$q$),
($q$SRC-72A0BD48B501$q$,$q$냉장 & 실온$q$,$q$원본 기준$q$,$q$$q$,$q$0+1$q$,$q$$q$,$q$$q$),
($q$SRC-29B8EE9621F4$q$,$q$냉장 & 실온$q$,$q$원본 기준$q$,$q$$q$,$q$2+1$q$,$q$$q$,$q$$q$),
($q$SRC-CA2B2D246444$q$,$q$냉장 & 실온$q$,$q$원본 기준$q$,$q$$q$,$q$2+1$q$,$q$$q$,$q$$q$),
($q$SRC-62C4A20C4039$q$,$q$냉장 & 실온$q$,$q$원본 기준$q$,$q$$q$,$q$-$q$,$q$$q$,$q$$q$),
($q$SRC-4BA4C3F49719$q$,$q$냉장 & 실온$q$,$q$원본 기준$q$,$q$$q$,$q$1+1$q$,$q$$q$,$q$$q$),
($q$SRC-508159BFBD25$q$,$q$냉장 & 실온$q$,$q$박스(b)/개$q$,$q$5~6개$q$,$q$대파9 / 블루베리12$q$,$q$2b$q$,$q$$q$),
($q$SRC-EB83EC07AFC5$q$,$q$냉장 & 실온$q$,$q$개/통$q$,$q$절반$q$,$q$0+소분 1통$q$,$q$1개$q$,$q$$q$),
($q$SRC-2AD26A89313E$q$,$q$냉장 & 실온$q$,$q$개$q$,$q$4개$q$,$q$2+1$q$,$q$4개$q$,$q$$q$),
($q$SRC-EDA3A0B9E3F5$q$,$q$냉장 & 실온$q$,$q$개/통$q$,$q$소분 절반$q$,$q$1캔+소분1통$q$,$q$1개$q$,$q$$q$),
($q$SRC-13E47C99D712$q$,$q$냉장 & 실온$q$,$q$원본 기준$q$,$q$$q$,$q$0+1$q$,$q$$q$,$q$$q$),
($q$SRC-FB7D09CCC992$q$,$q$냉장 & 실온$q$,$q$개$q$,$q$1개$q$,$q$0+1$q$,$q$1개$q$,$q$$q$),
($q$SRC-8DF92EFD3173$q$,$q$냉장 & 실온$q$,$q$원본 기준$q$,$q$$q$,$q$0+1$q$,$q$$q$,$q$$q$),
($q$SRC-54F109477430$q$,$q$냉장 & 실온$q$,$q$봉$q$,$q$$q$,$q$-$q$,$q$1봉$q$,$q$*월2,수3,목3 발주 / 수금토 입고$q$),
($q$SRC-95BB574CECA8$q$,$q$원두 & 우유 & 탄산$q$,$q$박스(b)$q$,$q$$q$,$q$사진$q$,$q$매주 (일) 2b$q$,$q$성수기엔 3-4b$q$),
($q$SRC-BB8084398355$q$,$q$원두 & 우유 & 탄산$q$,$q$박스(b)/봉$q$,$q$7봉지$q$,$q$사진$q$,$q$1b$q$,$q$성수기엔 10봉지-1b$q$),
($q$SRC-015AE855A123$q$,$q$원두 & 우유 & 탄산$q$,$q$박스(b)$q$,$q$우유냉장고 한칸$q$,$q$사진$q$,$q$2b$q$,$q$주말 겹칠땐 가득채우기 (2박스 시키면 한칸참)$q$),
($q$SRC-FF5212677A2F$q$,$q$원두 & 우유 & 탄산$q$,$q$개$q$,$q$4개$q$,$q$9개$q$,$q$쿠팡구매요청$q$,$q$$q$),
($q$SRC-1B8BC96BFA70$q$,$q$원두 & 우유 & 탄산$q$,$q$개$q$,$q$$q$,$q$1개$q$,$q$$q$,$q$$q$),
($q$SRC-78FC877FE22B$q$,$q$원두 & 우유 & 탄산$q$,$q$박스(b)$q$,$q$매장1 야창1일때$q$,$q$매장 절반이상 / 야창 4b$q$,$q$1b$q$,$q$$q$),
($q$SRC-E6FF521D1BA7$q$,$q$원두 & 우유 & 탄산$q$,$q$박스(b)$q$,$q$막개봉$q$,$q$매장 절반이상 / 야창 4b$q$,$q$2b$q$,$q$$q$),
($q$SRC-13B89D0B442F$q$,$q$원두 & 우유 & 탄산$q$,$q$박스(b)/개$q$,$q$$q$,$q$매장 1b+2개$q$,$q$$q$,$q$$q$),
($q$SRC-90AE885D4438$q$,$q$빙수$q$,$q$원본 기준$q$,$q$$q$,$q$-$q$,$q$$q$,$q$$q$),
($q$SRC-5D0CB796819D$q$,$q$빙수$q$,$q$원본 기준$q$,$q$$q$,$q$0+1$q$,$q$$q$,$q$$q$),
($q$SRC-6029537B69AD$q$,$q$빙수$q$,$q$통$q$,$q$1/3통$q$,$q$절반이상$q$,$q$$q$,$q$$q$),
($q$SRC-468A921A3D5B$q$,$q$빙수$q$,$q$줄$q$,$q$$q$,$q$매장 2.5줄 / 야창 1줄$q$,$q$$q$,$q$$q$),
($q$SRC-EC70801A6B54$q$,$q$빙수$q$,$q$줄$q$,$q$$q$,$q$매장 1줄 / 야창 -$q$,$q$$q$,$q$$q$),
($q$SRC-455E5095927A$q$,$q$빙수$q$,$q$줄$q$,$q$$q$,$q$매장 0.5줄 / 야창 -$q$,$q$$q$,$q$$q$),
($q$SRC-A1B7CE2273AD$q$,$q$빙수$q$,$q$박스(b)$q$,$q$냉동실 옮기면$q$,$q$매장 - / 야창 절반이상$q$,$q$1b$q$,$q$$q$)
) update public.inventory_items i set category=v.category,source_unit_system=v.unit_system,source_minimum_text=v.minimum_text,source_current_text=v.current_text,source_order_text=v.order_text,source_note=v.note,is_demo=false,is_active=true,updated_at=now() from v where i.sku=v.sku;

create or replace function public.admin_inventory_overview_v2()
returns table(id bigint,sku text,name text,unit text,is_active boolean,on_hand numeric,reorder_level numeric,inventory_value numeric,low_stock boolean,category text,source_unit_system text,source_minimum_text text,source_current_text text,source_order_text text,source_note text)
language plpgsql security definer set search_path='public','pg_temp' as $$ begin if not public.is_admin() then raise exception 'NOT_AUTHORIZED'; end if; return query select i.id,i.sku,i.name,i.unit,i.is_active,coalesce(sum(m.quantity),0)::numeric,i.reorder_level,coalesce(sum(m.quantity*coalesce(m.unit_cost,0)),0)::numeric,(i.reorder_level is not null and coalesce(sum(m.quantity),0)<=i.reorder_level),i.category,i.source_unit_system,i.source_minimum_text,i.source_current_text,i.source_order_text,i.source_note from public.inventory_items i left join public.inventory_movements m on m.item_id=i.id group by i.id order by i.is_active desc,i.name; end $$;

-- Recipe source tables contain the supplied PDF extraction (235 variants / 847 ingredient lines).
-- Store/staff list RPCs are source-first so source quantities are not hidden by empty legacy recipe_components.
create or replace function public.admin_store_recipe_list(p_store_id bigint)
returns table(product_id bigint,recipe_version_id bigint,menu_key text,menu_name text,category text,thumbnail_url text,instructions jsonb,components jsonb,is_overridden boolean,assignment_status text,retirement_requested_at timestamptz)
language plpgsql security definer set search_path='public','pg_temp' as $$ begin if not public.can_manage_store(p_store_id) then raise exception 'NOT_AUTHORIZED'; end if; return query with src as (select v.menu_name,min(v.category) category from public.recipe_source_variants v group by v.menu_name), base as (select hp.id product_id,hp.recipe_version_id,coalesce(hp.product_key,'source_'||md5(s.menu_name)) menu_key,s.menu_name,s.category,rv.thumbnail_url,public.source_recipe_instructions(s.menu_name) instructions,public.source_recipe_components(s.menu_name) components from src s left join lateral (select p.* from public.hq_products p where p.status='ACTIVE' and regexp_replace(lower(p.name),'[^0-9a-z가-힣]','','g')=regexp_replace(lower(s.menu_name),'[^0-9a-z가-힣]','','g') order by p.id limit 1) hp on true left join public.recipe_versions rv on rv.id=hp.recipe_version_id) select b.product_id,b.recipe_version_id,b.menu_key,coalesce(nullif(o.menu_name,''),b.menu_name),coalesce(nullif(o.category,''),b.category),coalesce(nullif(o.thumbnail_url,''),b.thumbnail_url),coalesce(o.instructions,b.instructions),case when o.store_id is null then b.components else o.components end,o.store_id is not null,'ACTIVE'::text,null::timestamptz from base b left join public.store_recipe_overrides o on o.store_id=p_store_id and o.menu_key=b.menu_key order by coalesce(nullif(o.category,''),b.category),coalesce(nullif(o.menu_name,''),b.menu_name); end $$;
