-- v0.83 purchase order / receiving schema mirror
create table if not exists public.inventory_purchase_orders (
 id bigint generated by default as identity primary key, store_id bigint not null references public.stores(id),
 item_id bigint references public.inventory_items(id), manual_item_id bigint references public.inventory_manual_items(id),
 item_name text not null, unit text not null, ordered_quantity numeric not null check(ordered_quantity>0),
 received_quantity numeric not null default 0 check(received_quantity>=0), status text not null default 'ORDERED',
 note text, ordered_by uuid default auth.uid(), ordered_at timestamptz not null default now(), received_at timestamptz, updated_at timestamptz not null default now(),
 check ((item_id is not null)::int+(manual_item_id is not null)::int=1), check(received_quantity<=ordered_quantity)
);
alter table public.inventory_purchase_orders enable row level security;
revoke all on public.inventory_purchase_orders from public,anon,authenticated;
create index if not exists inventory_purchase_orders_store_status_idx on public.inventory_purchase_orders(store_id,status,ordered_at desc);
-- Functions are installed in production by Supabase migration inventory_purchase_receiving_v083; keep this file as schema history.
