-- HQ product rollout control: draft -> all-store launch/discontinue.
create table if not exists public.hq_products (
  id bigint generated by default as identity primary key,
  product_key text not null unique,
  name text not null,
  category text,
  status text not null default 'DRAFT' check (status in ('DRAFT','ACTIVE','DISCONTINUED')),
  effective_from date,
  effective_to date,
  sale_aliases text[] not null default '{}',
  purchase_aliases text[] not null default '{}',
  component_blueprint jsonb not null default '[]'::jsonb check (jsonb_typeof(component_blueprint)='array'),
  recipe_version_id bigint references public.recipe_versions(id),
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (effective_to is null or effective_from is null or effective_to >= effective_from)
);

create table if not exists public.hq_product_items (
  product_id bigint not null references public.hq_products(id) on delete cascade,
  item_id bigint not null references public.inventory_items(id),
  quantity numeric not null check (quantity > 0),
  created_by_hq boolean not null default false,
  primary key (product_id,item_id)
);

create table if not exists public.store_product_assignments (
  product_id bigint not null references public.hq_products(id) on delete cascade,
  store_id bigint not null references public.stores(id),
  status text not null check (status in ('ACTIVE','DISCONTINUED')),
  applied_at timestamptz not null default now(),
  discontinued_at timestamptz,
  primary key (product_id,store_id)
);

create table if not exists public.hq_product_transaction_links (
  product_id bigint not null references public.hq_products(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('SALE','PURCHASE')),
  alias text not null,
  primary key (product_id,transaction_type,alias)
);

create table if not exists public.hq_product_rollouts (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.hq_products(id),
  action text not null check (action in ('LAUNCH','DISCONTINUE')),
  affected_store_count integer not null default 0,
  recipe_version_id bigint references public.recipe_versions(id),
  details jsonb not null default '{}'::jsonb,
  actor_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists store_product_assignments_store_status_idx
  on public.store_product_assignments(store_id,status);
create index if not exists hq_product_transaction_links_alias_idx
  on public.hq_product_transaction_links(transaction_type,lower(alias));
create index if not exists hq_product_rollouts_product_created_idx
  on public.hq_product_rollouts(product_id,created_at desc);

alter table public.hq_products enable row level security;
alter table public.hq_product_items enable row level security;
alter table public.store_product_assignments enable row level security;
alter table public.hq_product_transaction_links enable row level security;
alter table public.hq_product_rollouts enable row level security;

revoke all on public.hq_products from anon, authenticated;
revoke all on public.hq_product_items from anon, authenticated;
revoke all on public.store_product_assignments from anon, authenticated;
revoke all on public.hq_product_transaction_links from anon, authenticated;
revoke all on public.hq_product_rollouts from anon, authenticated;

create or replace function public.admin_hq_product_list()
returns table(
  id bigint, product_key text, name text, category text, status text,
  effective_from date, effective_to date, sale_aliases text[], purchase_aliases text[],
  component_blueprint jsonb, recipe_version_id bigint,
  active_store_count bigint, total_store_count bigint,
  sales_30d numeric, purchases_30d numeric, updated_at timestamptz
)
language plpgsql security definer set search_path='public','pg_temp'
as $function$
begin
  if not public.is_admin() then raise exception 'NOT_AUTHORIZED'; end if;
  return query
  select p.id,p.product_key,p.name,p.category,p.status,p.effective_from,p.effective_to,
    p.sale_aliases,p.purchase_aliases,p.component_blueprint,p.recipe_version_id,
    (select count(*) from public.store_product_assignments a where a.product_id=p.id and a.status='ACTIVE'),
    (select count(*) from public.stores s where s.is_active),
    coalesce((select sum(t.total_amount) from public.operations_transactions t
      where t.transaction_type='SALE' and t.transacted_at>=now()-interval '30 days'
        and exists(select 1 from public.hq_product_transaction_links l where l.product_id=p.id
          and l.transaction_type='SALE' and lower(l.alias)=lower(t.counterparty))),0),
    coalesce((select sum(t.total_amount) from public.operations_transactions t
      where t.transaction_type='PURCHASE' and t.transacted_at>=now()-interval '30 days'
        and exists(select 1 from public.hq_product_transaction_links l where l.product_id=p.id
          and l.transaction_type='PURCHASE' and lower(l.alias)=lower(t.counterparty))),0),
    p.updated_at
  from public.hq_products p
  order by case p.status when 'ACTIVE' then 0 when 'DRAFT' then 1 else 2 end,p.updated_at desc,p.name;
end
$function$;

create or replace function public.admin_hq_product_save(p_product_id bigint, p_payload jsonb)
returns bigint
language plpgsql security definer set search_path='public','pg_temp'
as $function$
declare
  v_id bigint;
  v_key text;
  v_name text;
  v_category text;
  v_components jsonb;
  v_comp jsonb;
begin
  if not public.is_admin() then raise exception 'NOT_AUTHORIZED'; end if;
  v_name:=trim(coalesce(p_payload->>'name',''));
  v_key:=upper(regexp_replace(trim(coalesce(p_payload->>'product_key','')),'[^A-Za-z0-9_-]+','-','g'));
  v_category:=nullif(trim(coalesce(p_payload->>'category','')),'');
  v_components:=coalesce(p_payload->'components','[]'::jsonb);
  if v_name='' then raise exception 'PRODUCT_NAME_REQUIRED'; end if;
  if v_key='' then raise exception 'PRODUCT_KEY_REQUIRED'; end if;
  if jsonb_typeof(v_components)<>'array' or jsonb_array_length(v_components)=0 then raise exception 'COMPONENT_REQUIRED'; end if;
  for v_comp in select * from jsonb_array_elements(v_components) loop
    if coalesce((v_comp->>'quantity')::numeric,0)<=0 then raise exception 'INVALID_COMPONENT_QUANTITY'; end if;
    if nullif(v_comp->>'item_id','') is null and
       (trim(coalesce(v_comp->>'sku',''))='' or trim(coalesce(v_comp->>'name',''))='' or trim(coalesce(v_comp->>'unit',''))='')
    then raise exception 'NEW_ITEM_FIELDS_REQUIRED'; end if;
  end loop;
  if p_product_id is null then
    insert into public.hq_products(product_key,name,category,sale_aliases,purchase_aliases,component_blueprint,created_by)
    values(v_key,v_name,v_category,
      array(select trim(x) from jsonb_array_elements_text(coalesce(p_payload->'sale_aliases','[]'::jsonb)) x where trim(x)<>''),
      array(select trim(x) from jsonb_array_elements_text(coalesce(p_payload->'purchase_aliases','[]'::jsonb)) x where trim(x)<>''),
      v_components,auth.uid()) returning id into v_id;
  else
    update public.hq_products set product_key=v_key,name=v_name,category=v_category,
      sale_aliases=array(select trim(x) from jsonb_array_elements_text(coalesce(p_payload->'sale_aliases','[]'::jsonb)) x where trim(x)<>''),
      purchase_aliases=array(select trim(x) from jsonb_array_elements_text(coalesce(p_payload->'purchase_aliases','[]'::jsonb)) x where trim(x)<>''),
      component_blueprint=v_components,updated_at=now()
    where id=p_product_id returning id into v_id;
    if v_id is null then raise exception 'PRODUCT_NOT_FOUND'; end if;
  end if;
  return v_id;
end
$function$;

create or replace function public.admin_hq_product_apply(p_product_id bigint, p_action text)
returns jsonb
language plpgsql security definer set search_path='public','pg_temp'
as $function$
declare
  p public.hq_products%rowtype;
  v_comp jsonb;
  v_item_id bigint;
  v_recipe_id bigint;
  v_created boolean;
  v_store_count integer:=0;
  v_action text:=upper(trim(coalesce(p_action,'')));
  v_alias text;
  v_old_hq_items bigint[]:='{}';
begin
  if not public.is_admin() then raise exception 'NOT_AUTHORIZED'; end if;
  if v_action not in ('LAUNCH','DISCONTINUE') then raise exception 'INVALID_ACTION'; end if;
  select * into p from public.hq_products where id=p_product_id for update;
  if p.id is null then raise exception 'PRODUCT_NOT_FOUND'; end if;

  if v_action='LAUNCH' then
    select coalesce(array_agg(item_id),'{}') into v_old_hq_items
      from public.hq_product_items where product_id=p.id and created_by_hq;
    delete from public.hq_product_items where product_id=p.id;
    for v_comp in select * from jsonb_array_elements(p.component_blueprint) loop
      v_item_id:=nullif(v_comp->>'item_id','')::bigint;
      v_created:=coalesce(v_item_id=any(v_old_hq_items),false);
      if v_item_id is not null then
        update public.inventory_items set is_active=true,updated_at=now() where id=v_item_id returning id into v_item_id;
        if v_item_id is null then raise exception 'INVENTORY_ITEM_NOT_FOUND'; end if;
      else
        select i.id into v_item_id from public.inventory_items i where lower(i.sku)=lower(trim(v_comp->>'sku')) limit 1;
        if v_item_id is null then
          insert into public.inventory_items(sku,name,unit,is_active,reorder_level,pack_quantity,pack_unit,is_demo)
          values(trim(v_comp->>'sku'),trim(v_comp->>'name'),trim(v_comp->>'unit'),true,
            nullif(v_comp->>'reorder_level','')::numeric,nullif(v_comp->>'pack_quantity','')::numeric,
            nullif(trim(coalesce(v_comp->>'pack_unit','')),''),false)
          returning id into v_item_id;
          v_created:=true;
        else
          v_created:=coalesce(v_item_id=any(v_old_hq_items),false);
          update public.inventory_items set name=trim(v_comp->>'name'),unit=trim(v_comp->>'unit'),is_active=true,
            reorder_level=coalesce(nullif(v_comp->>'reorder_level','')::numeric,reorder_level),
            pack_quantity=coalesce(nullif(v_comp->>'pack_quantity','')::numeric,pack_quantity),
            pack_unit=coalesce(nullif(trim(coalesce(v_comp->>'pack_unit','')),''),pack_unit),updated_at=now()
          where id=v_item_id;
        end if;
      end if;
      insert into public.hq_product_items(product_id,item_id,quantity,created_by_hq)
      values(p.id,v_item_id,(v_comp->>'quantity')::numeric,v_created)
      on conflict(product_id,item_id) do update set quantity=excluded.quantity,
        created_by_hq=public.hq_product_items.created_by_hq or excluded.created_by_hq;
    end loop;

    if p.recipe_version_id is not null then
      update public.recipe_versions set effective_to=current_date where id=p.recipe_version_id and effective_to is null;
    end if;
    insert into public.recipe_versions(menu_key,menu_name,category,effective_from,effective_to,is_demo)
    values(p.product_key,p.name,p.category,current_date,null,false) returning id into v_recipe_id;
    insert into public.recipe_components(recipe_version_id,item_id,quantity)
      select v_recipe_id,item_id,quantity from public.hq_product_items where product_id=p.id;

    insert into public.store_product_assignments(product_id,store_id,status,applied_at,discontinued_at)
      select p.id,s.id,'ACTIVE',now(),null from public.stores s where s.is_active
      on conflict(product_id,store_id) do update set status='ACTIVE',applied_at=now(),discontinued_at=null;
    get diagnostics v_store_count=row_count;

    delete from public.hq_product_transaction_links where product_id=p.id;
    foreach v_alias in array p.sale_aliases loop
      insert into public.hq_product_transaction_links values(p.id,'SALE',v_alias) on conflict do nothing;
    end loop;
    foreach v_alias in array p.purchase_aliases loop
      insert into public.hq_product_transaction_links values(p.id,'PURCHASE',v_alias) on conflict do nothing;
    end loop;
    update public.hq_products set status='ACTIVE',effective_from=current_date,effective_to=null,
      recipe_version_id=v_recipe_id,updated_at=now() where id=p.id;
  else
    if p.recipe_version_id is not null then
      update public.recipe_versions set effective_to=current_date where id=p.recipe_version_id and effective_to is null;
    end if;
    update public.store_product_assignments set status='DISCONTINUED',discontinued_at=now()
      where product_id=p.id and status='ACTIVE';
    get diagnostics v_store_count=row_count;
    update public.inventory_items i set is_active=false,updated_at=now()
      where exists(select 1 from public.hq_product_items pi where pi.product_id=p.id and pi.item_id=i.id and pi.created_by_hq)
        and not exists(select 1 from public.hq_product_items pi2 join public.hq_products p2 on p2.id=pi2.product_id
          where pi2.item_id=i.id and p2.id<>p.id and p2.status='ACTIVE');
    update public.hq_products set status='DISCONTINUED',effective_to=current_date,updated_at=now() where id=p.id;
    v_recipe_id:=p.recipe_version_id;
  end if;

  insert into public.hq_product_rollouts(product_id,action,affected_store_count,recipe_version_id,details,actor_id)
  values(p.id,v_action,v_store_count,v_recipe_id,
    jsonb_build_object('product_key',p.product_key,'name',p.name,'component_count',jsonb_array_length(p.component_blueprint)),auth.uid());
  return jsonb_build_object('ok',true,'action',v_action,'product_id',p.id,'affected_store_count',v_store_count,'recipe_version_id',v_recipe_id);
end
$function$;

-- Remove presentation-only demo prefixes from stored recipe names as requested.
update public.recipe_versions
set menu_name=regexp_replace(menu_name,'^\s*\[예시\]\s*','')
where menu_name ~ '^\s*\[예시\]';

-- Demo fixtures stay out of the registered management list; historical rows remain intact.
create or replace function public.admin_recipe_list_v2()
returns table(id bigint, menu_key text, menu_name text, category text, effective_from date, effective_to date, is_demo boolean, thumbnail_url text, components jsonb)
language plpgsql security definer set search_path='public','pg_temp'
as $function$
begin
  if not public.is_admin() then raise exception 'NOT_AUTHORIZED'; end if;
  return query select r.id,r.menu_key,r.menu_name,r.category,r.effective_from,r.effective_to,r.is_demo,r.thumbnail_url,
    coalesce(jsonb_agg(jsonb_build_object('item_id',i.id,'item_name',i.name,'unit',i.unit,'quantity',c.quantity) order by i.name)
      filter(where i.id is not null),'[]'::jsonb)
  from public.recipe_versions r
  left join public.recipe_components c on c.recipe_version_id=r.id
  left join public.inventory_items i on i.id=c.item_id
  where r.effective_to is null and not r.is_demo
  group by r.id order by r.menu_name,r.effective_from desc;
end
$function$;

revoke all on function public.admin_hq_product_list() from public, anon;
revoke all on function public.admin_hq_product_save(bigint,jsonb) from public, anon;
revoke all on function public.admin_hq_product_apply(bigint,text) from public, anon;
grant execute on function public.admin_hq_product_list() to authenticated;
grant execute on function public.admin_hq_product_save(bigint,jsonb) to authenticated;
grant execute on function public.admin_hq_product_apply(bigint,text) to authenticated;
