-- v220: top-level recipe access, store-scoped overrides, and stock-safe retirement.

alter table public.admin_users
  add column if not exists admin_role text not null default 'HQ'
    check (admin_role in ('HQ','STORE_MANAGER')),
  add column if not exists store_id bigint references public.stores(id);

create or replace function public.is_hq_admin()
returns boolean
language sql stable security definer set search_path='public','pg_temp'
as $function$
  select exists(
    select 1 from public.admin_users a
    where a.user_id=(select auth.uid()) and a.admin_role='HQ'
  )
$function$;

create or replace function public.can_manage_store(p_store_id bigint)
returns boolean
language sql stable security definer set search_path='public','pg_temp'
as $function$
  select exists(
    select 1 from public.admin_users a
    where a.user_id=(select auth.uid())
      and (a.admin_role='HQ' or (a.admin_role='STORE_MANAGER' and a.store_id=p_store_id))
  )
$function$;

create or replace function public.admin_context()
returns jsonb
language sql stable security definer set search_path='public','pg_temp'
as $function$
  select coalesce(
    (select jsonb_build_object('role',a.admin_role,'store_id',a.store_id,'email',a.email)
       from public.admin_users a where a.user_id=(select auth.uid())),
    jsonb_build_object('role',null,'store_id',null,'email',null)
  )
$function$;

create table if not exists public.store_recipe_overrides(
  store_id bigint not null references public.stores(id) on delete cascade,
  menu_key text not null,
  menu_name text,
  category text,
  thumbnail_url text,
  instructions jsonb check(instructions is null or jsonb_typeof(instructions)='array'),
  components jsonb not null default '[]'::jsonb check(jsonb_typeof(components)='array'),
  updated_by uuid default auth.uid(),
  updated_at timestamptz not null default now(),
  primary key(store_id,menu_key)
);
alter table public.store_recipe_overrides enable row level security;

create table if not exists public.store_notifications(
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  notification_type text not null,
  product_id bigint references public.hq_products(id) on delete cascade,
  title text not null,
  message text,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
alter table public.store_notifications enable row level security;
create index if not exists store_notifications_store_unread_idx
  on public.store_notifications(store_id,is_read,created_at desc);

alter table public.inventory_manual_items
  add column if not exists source_item_id bigint references public.inventory_items(id);
create index if not exists inventory_manual_items_source_idx
  on public.inventory_manual_items(store_id,source_item_id);
update public.inventory_manual_items m
set source_item_id=i.id
from public.inventory_items i
where m.source_item_id is null and lower(trim(m.name))=lower(trim(i.name));

alter table public.store_product_assignments drop constraint if exists store_product_assignments_status_check;
alter table public.store_product_assignments
  add constraint store_product_assignments_status_check
  check(status in ('ACTIVE','RETIRING','DISCONTINUED'));
alter table public.store_product_assignments
  add column if not exists retirement_requested_at timestamptz,
  add column if not exists retirement_completed_at timestamptz;

create or replace function public.protect_store_product_retirement()
returns trigger
language plpgsql set search_path='public','pg_temp'
as $function$
begin
  if old.status='ACTIVE' and new.status='DISCONTINUED' then
    new.status:='RETIRING';
    new.discontinued_at:=null;
    new.retirement_requested_at:=now();
    new.retirement_completed_at:=null;
  elsif new.status='ACTIVE' then
    new.retirement_requested_at:=null;
    new.retirement_completed_at:=null;
  end if;
  return new;
end
$function$;
drop trigger if exists protect_store_product_retirement on public.store_product_assignments;
create trigger protect_store_product_retirement
before update on public.store_product_assignments
for each row execute function public.protect_store_product_retirement();

create or replace function public.notify_store_product_retirement()
returns trigger
language plpgsql set search_path='public','pg_temp'
as $function$
declare v_name text;
begin
  if old.status is distinct from 'RETIRING' and new.status='RETIRING' then
    select name into v_name from public.hq_products where id=new.product_id;
    insert into public.store_notifications(store_id,notification_type,product_id,title,message)
    values(new.store_id,'PRODUCT_RETIRING',new.product_id,
      coalesce(v_name,'상품')||' 판매 종료 안내',
      '전용 재료 재고를 소진한 뒤 레시피 화면에서 판매 종료를 확정하세요.');
  end if;
  return new;
end
$function$;
drop trigger if exists notify_store_product_retirement on public.store_product_assignments;
create trigger notify_store_product_retirement
after update on public.store_product_assignments
for each row execute function public.notify_store_product_retirement();

create or replace function public.keep_inventory_for_retiring_products()
returns trigger
language plpgsql set search_path='public','pg_temp'
as $function$
begin
  if old.is_active and not new.is_active and exists(
    select 1 from public.hq_product_items pi
    join public.store_product_assignments a on a.product_id=pi.product_id
    where pi.item_id=old.id and a.status='RETIRING'
  ) then new.is_active:=true; end if;
  return new;
end
$function$;
drop trigger if exists keep_inventory_for_retiring_products on public.inventory_items;
create trigger keep_inventory_for_retiring_products
before update of is_active on public.inventory_items
for each row execute function public.keep_inventory_for_retiring_products();

create or replace function public.admin_store_recipe_list(p_store_id bigint)
returns table(
  product_id bigint, recipe_version_id bigint, menu_key text, menu_name text,
  category text, thumbnail_url text, instructions jsonb, components jsonb, is_overridden boolean,
  assignment_status text, retirement_requested_at timestamptz
)
language plpgsql security definer set search_path='public','pg_temp'
as $function$
begin
  if not public.can_manage_store(p_store_id) then raise exception 'NOT_AUTHORIZED'; end if;
  return query
  with base as (
    select p.id product_id,p.recipe_version_id,p.product_key menu_key,p.name menu_name,
      p.category,r.thumbnail_url,a.status assignment_status,a.retirement_requested_at,
      coalesce(jsonb_agg(jsonb_build_object(
        'item_id',i.id,'item_name',i.name,'unit',i.unit,'quantity',c.quantity
      ) order by i.name) filter(where i.id is not null),'[]'::jsonb) components
    from public.hq_products p
    join public.store_product_assignments a on a.product_id=p.id and a.store_id=p_store_id
    left join public.recipe_versions r on r.id=p.recipe_version_id
    left join public.recipe_components c on c.recipe_version_id=r.id
    left join public.inventory_items i on i.id=c.item_id
    where a.status in ('ACTIVE','RETIRING')
    group by p.id,p.recipe_version_id,p.product_key,p.name,p.category,r.thumbnail_url,a.status,a.retirement_requested_at
  )
  select b.product_id,b.recipe_version_id,b.menu_key,
    coalesce(nullif(o.menu_name,''),b.menu_name),
    coalesce(nullif(o.category,''),b.category),
    coalesce(nullif(o.thumbnail_url,''),b.thumbnail_url),o.instructions,
    case when o.store_id is null then b.components else o.components end,
    o.store_id is not null,b.assignment_status,b.retirement_requested_at
  from base b left join public.store_recipe_overrides o
    on o.store_id=p_store_id and o.menu_key=b.menu_key
  order by coalesce(nullif(o.category,''),b.category) nulls last,
    coalesce(nullif(o.menu_name,''),b.menu_name);
end
$function$;

create or replace function public.staff_recipe_list(
  p_employee_id bigint,p_pin text,p_store_id bigint
)
returns table(
  product_id bigint, recipe_version_id bigint, menu_key text, menu_name text,
  category text, thumbnail_url text, instructions jsonb, components jsonb,
  assignment_status text, retirement_requested_at timestamptz
)
language plpgsql security definer set search_path='public','extensions','pg_temp'
as $function$
declare v_last_type text;
begin
  if not exists(
    select 1 from public.employees e
    where e.id=p_employee_id and e.store_id=p_store_id and e.is_active
      and e.pin_bcrypt=crypt(p_pin,e.pin_bcrypt)
  ) then raise exception 'BAD_PIN'; end if;
  select ae.event_type into v_last_type
  from public.attendance_events ae
  where ae.employee_id=p_employee_id order by ae.id desc limit 1;
  if coalesce(v_last_type,'OUT')<>'IN' then raise exception 'NOT_CLOCKED_IN'; end if;

  return query
  with base as (
    select p.id product_id,p.recipe_version_id,p.product_key menu_key,p.name menu_name,
      p.category,r.thumbnail_url,a.status assignment_status,a.retirement_requested_at,
      coalesce(jsonb_agg(jsonb_build_object(
        'item_id',i.id,'item_name',i.name,'unit',i.unit,'quantity',c.quantity
      ) order by i.name) filter(where i.id is not null),'[]'::jsonb) components
    from public.hq_products p
    join public.store_product_assignments a on a.product_id=p.id and a.store_id=p_store_id
    left join public.recipe_versions r on r.id=p.recipe_version_id
    left join public.recipe_components c on c.recipe_version_id=r.id
    left join public.inventory_items i on i.id=c.item_id
    where a.status in ('ACTIVE','RETIRING')
    group by p.id,p.recipe_version_id,p.product_key,p.name,p.category,r.thumbnail_url,a.status,a.retirement_requested_at
  )
  select b.product_id,b.recipe_version_id,b.menu_key,
    coalesce(nullif(o.menu_name,''),b.menu_name),
    coalesce(nullif(o.category,''),b.category),
    coalesce(nullif(o.thumbnail_url,''),b.thumbnail_url),o.instructions,
    case when o.store_id is null then b.components else o.components end,
    b.assignment_status,b.retirement_requested_at
  from base b left join public.store_recipe_overrides o
    on o.store_id=p_store_id and o.menu_key=b.menu_key
  order by coalesce(nullif(o.category,''),b.category) nulls last,
    coalesce(nullif(o.menu_name,''),b.menu_name);
end
$function$;

create or replace function public.admin_store_recipe_override_save(
  p_store_id bigint,p_menu_key text,p_menu_name text,p_category text,
  p_components jsonb,p_thumbnail_url text,p_instructions jsonb default null
)
returns jsonb
language plpgsql security definer set search_path='public','pg_temp'
as $function$
declare v_comp jsonb; v_item public.inventory_items%rowtype; v_normalized jsonb='[]'::jsonb;
begin
  if not public.can_manage_store(p_store_id) then raise exception 'NOT_AUTHORIZED'; end if;
  if not exists(
    select 1 from public.hq_products p join public.store_product_assignments a on a.product_id=p.id
    where p.product_key=p_menu_key and a.store_id=p_store_id and a.status in ('ACTIVE','RETIRING')
  ) then raise exception 'RECIPE_NOT_FOUND'; end if;
  if jsonb_typeof(p_components)<>'array' or jsonb_array_length(p_components)=0 then
    raise exception 'COMPONENT_REQUIRED';
  end if;
  for v_comp in select * from jsonb_array_elements(p_components) loop
    select * into v_item from public.inventory_items
    where id=nullif(v_comp->>'item_id','')::bigint and is_active;
    if v_item.id is null or coalesce((v_comp->>'quantity')::numeric,0)<=0 then
      raise exception 'INVALID_COMPONENT';
    end if;
    v_normalized:=v_normalized||jsonb_build_array(jsonb_build_object(
      'item_id',v_item.id,'item_name',v_item.name,'unit',v_item.unit,
      'quantity',(v_comp->>'quantity')::numeric
    ));
  end loop;
  if p_instructions is not null and jsonb_typeof(p_instructions)<>'array' then
    raise exception 'INVALID_INSTRUCTIONS';
  end if;
  insert into public.store_recipe_overrides(
    store_id,menu_key,menu_name,category,thumbnail_url,instructions,components,updated_by,updated_at
  ) values(
    p_store_id,p_menu_key,nullif(trim(p_menu_name),''),nullif(trim(p_category),''),
    nullif(trim(p_thumbnail_url),''),p_instructions,v_normalized,auth.uid(),now()
  ) on conflict(store_id,menu_key) do update set
    menu_name=excluded.menu_name,category=excluded.category,
    thumbnail_url=excluded.thumbnail_url,instructions=excluded.instructions,components=excluded.components,
    updated_by=auth.uid(),updated_at=now();
  return jsonb_build_object('ok',true,'store_id',p_store_id,'menu_key',p_menu_key);
end
$function$;

create or replace function public.admin_store_recipe_override_clear(
  p_store_id bigint,p_menu_key text
)
returns jsonb
language plpgsql security definer set search_path='public','pg_temp'
as $function$
begin
  if not public.can_manage_store(p_store_id) then raise exception 'NOT_AUTHORIZED'; end if;
  delete from public.store_recipe_overrides where store_id=p_store_id and menu_key=p_menu_key;
  return jsonb_build_object('ok',true);
end
$function$;

create or replace function public.admin_store_product_retirement_finalize(
  p_store_id bigint,p_product_id bigint
)
returns jsonb
language plpgsql security definer set search_path='public','pg_temp'
as $function$
declare v_positive jsonb; v_untracked jsonb;
begin
  if not public.can_manage_store(p_store_id) then raise exception 'NOT_AUTHORIZED'; end if;
  if not exists(select 1 from public.store_product_assignments where store_id=p_store_id and product_id=p_product_id and status='RETIRING') then
    raise exception 'RETIREMENT_NOT_PENDING';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object('name',i.name,'on_hand',m.on_hand,'unit',m.unit)),'[]'::jsonb)
  into v_positive
  from public.hq_product_items pi
  join public.inventory_items i on i.id=pi.item_id
  join public.inventory_manual_items m on m.store_id=p_store_id and m.source_item_id=i.id and m.is_active
  where pi.product_id=p_product_id and pi.created_by_hq and m.on_hand>0;

  select coalesce(jsonb_agg(jsonb_build_object('item_id',i.id,'name',i.name)),'[]'::jsonb)
  into v_untracked
  from public.hq_product_items pi
  join public.inventory_items i on i.id=pi.item_id
  where pi.product_id=p_product_id and pi.created_by_hq
    and not exists(select 1 from public.inventory_manual_items m where m.store_id=p_store_id and m.source_item_id=i.id and m.is_active);

  if jsonb_array_length(v_positive)>0 then
    return jsonb_build_object('ok',false,'error','STOCK_REMAINS','items',v_positive);
  end if;
  if jsonb_array_length(v_untracked)>0 then
    return jsonb_build_object('ok',false,'error','STOCK_NOT_TRACKED','items',v_untracked);
  end if;

  update public.store_product_assignments set status='DISCONTINUED',discontinued_at=now(),retirement_completed_at=now()
  where store_id=p_store_id and product_id=p_product_id and status='RETIRING';

  update public.inventory_items i set is_active=false,updated_at=now()
  where exists(select 1 from public.hq_product_items pi where pi.product_id=p_product_id and pi.item_id=i.id and pi.created_by_hq)
    and not exists(
      select 1 from public.hq_product_items pi2 join public.hq_products p2 on p2.id=pi2.product_id
      where pi2.item_id=i.id and p2.id<>p_product_id and p2.status='ACTIVE'
    )
    and not exists(
      select 1 from public.store_product_assignments a
      join public.hq_product_items pi3 on pi3.product_id=a.product_id and pi3.item_id=i.id
      where a.status in ('ACTIVE','RETIRING')
    );
  return jsonb_build_object('ok',true,'status','DISCONTINUED');
end
$function$;

create or replace function public.admin_inventory_manual_save_v2(
  p_id bigint,p_store_id bigint,p_name text,p_sku text,p_category text,
  p_unit text,p_on_hand numeric,p_target_level numeric,p_reorder_point numeric,
  p_thumbnail_url text,p_source_item_id bigint default null
)
returns public.inventory_manual_items
language plpgsql security definer set search_path='public','pg_temp'
as $function$
declare r public.inventory_manual_items; v_source public.inventory_items%rowtype;
begin
  if not public.can_manage_store(p_store_id) then raise exception 'NOT_AUTHORIZED'; end if;
  if coalesce(p_on_hand,0)<0 or coalesce(p_target_level,0)<0 or coalesce(p_reorder_point,0)<0 then raise exception 'INVALID_STOCK'; end if;
  if coalesce(p_target_level,0)>0 and coalesce(p_reorder_point,0)>coalesce(p_target_level,0) then raise exception 'INVALID_REORDER_POINT'; end if;
  if p_source_item_id is not null then
    select * into v_source from public.inventory_items where id=p_source_item_id and is_active;
    if v_source.id is null then raise exception 'INVENTORY_ITEM_NOT_FOUND'; end if;
    p_name:=v_source.name; p_sku:=v_source.sku; p_unit:=v_source.unit;
  elsif nullif(trim(p_name),'') is null then
    raise exception 'NAME_REQUIRED';
  end if;
  if p_id is null then
    insert into public.inventory_manual_items(store_id,name,sku,category,unit,on_hand,target_level,reorder_point,thumbnail_url,source_item_id)
    values(p_store_id,trim(p_name),nullif(trim(p_sku),''),nullif(trim(p_category),''),coalesce(nullif(trim(p_unit),''),'ea'),coalesce(p_on_hand,0),coalesce(p_target_level,0),coalesce(p_reorder_point,0),nullif(trim(p_thumbnail_url),''),p_source_item_id)
    on conflict(store_id,name) do update set sku=excluded.sku,category=excluded.category,unit=excluded.unit,on_hand=excluded.on_hand,target_level=excluded.target_level,reorder_point=excluded.reorder_point,thumbnail_url=excluded.thumbnail_url,source_item_id=coalesce(excluded.source_item_id,public.inventory_manual_items.source_item_id),updated_at=now()
    returning * into r;
  else
    update public.inventory_manual_items set name=trim(p_name),sku=nullif(trim(p_sku),''),category=nullif(trim(p_category),''),unit=coalesce(nullif(trim(p_unit),''),'ea'),on_hand=coalesce(p_on_hand,0),target_level=coalesce(p_target_level,0),reorder_point=coalesce(p_reorder_point,0),thumbnail_url=nullif(trim(p_thumbnail_url),''),source_item_id=coalesce(p_source_item_id,source_item_id),updated_at=now()
    where id=p_id and store_id=p_store_id returning * into r;
  end if;
  if r.id is null then raise exception 'INVENTORY_SAVE_FAILED'; end if;
  return r;
end
$function$;

-- Keep a recoverable copy, then remove the 24 known demo recipe rows from production lists.
create table if not exists public.recipe_versions_demo_archive
(like public.recipe_versions including defaults);
create table if not exists public.recipe_components_demo_archive
(like public.recipe_components including defaults);
alter table public.recipe_versions_demo_archive enable row level security;
alter table public.recipe_components_demo_archive enable row level security;
insert into public.recipe_versions_demo_archive
select * from public.recipe_versions where is_demo
on conflict do nothing;
insert into public.recipe_components_demo_archive
select c.* from public.recipe_components c join public.recipe_versions r on r.id=c.recipe_version_id where r.is_demo
on conflict do nothing;
delete from public.recipe_components c using public.recipe_versions r
where c.recipe_version_id=r.id and r.is_demo;
delete from public.recipe_versions where is_demo;

revoke all on function public.is_hq_admin() from public,anon;
revoke all on function public.can_manage_store(bigint) from public,anon;
revoke all on function public.admin_context() from public,anon;
revoke all on function public.admin_store_recipe_list(bigint) from public,anon;
revoke all on function public.staff_recipe_list(bigint,text,bigint) from public;
revoke all on function public.admin_store_recipe_override_save(bigint,text,text,text,jsonb,text,jsonb) from public,anon;
revoke all on function public.admin_store_recipe_override_clear(bigint,text) from public,anon;
revoke all on function public.admin_store_product_retirement_finalize(bigint,bigint) from public,anon;
revoke all on function public.admin_inventory_manual_save_v2(bigint,bigint,text,text,text,text,numeric,numeric,numeric,text,bigint) from public,anon;
revoke all on function public.protect_store_product_retirement() from public,anon,authenticated;
revoke all on function public.notify_store_product_retirement() from public,anon,authenticated;
revoke all on function public.keep_inventory_for_retiring_products() from public,anon,authenticated;
grant execute on function public.admin_context() to authenticated;
grant execute on function public.admin_store_recipe_list(bigint) to authenticated;
grant execute on function public.staff_recipe_list(bigint,text,bigint) to anon,authenticated;
grant execute on function public.admin_store_recipe_override_save(bigint,text,text,text,jsonb,text,jsonb) to authenticated;
grant execute on function public.admin_store_recipe_override_clear(bigint,text) to authenticated;
grant execute on function public.admin_store_product_retirement_finalize(bigint,bigint) to authenticated;
grant execute on function public.admin_inventory_manual_save_v2(bigint,bigint,text,text,text,text,numeric,numeric,numeric,text,bigint) to authenticated;

grant select,insert,update,delete on public.store_recipe_overrides to authenticated;
grant select,insert,update on public.store_notifications to authenticated;
