const CONFIG={SUPABASE_URL:"https://waluhdgqhwjjwmflhrle.supabase.co",SUPABASE_ANON_KEY:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhbHVoZGdxaHdqandtZmxocmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2MTg4NjAsImV4cCI6MjEwMzE5NDg2MH0.-UugGE05V70Ecw__UdIZpWJr2mDYmLfV7mh_lR-U9Mw"};
const Auth={token:null,load(){try{this.token=JSON.parse(localStorage.getItem('baekeok_auth'))?.access_token||null}catch(_){this.token=null}return this.token}};
async function rpc(fn,args={}){const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/rpc/${fn}`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${Auth.token||CONFIG.SUPABASE_ANON_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(args)});const t=await r.text();if(!r.ok)throw new Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):null}
const el=id=>document.getElementById(id);let decision='NEEDS_REVIEW',employees=[];
function toast(msg,err=false){const x=el('toast');x.textContent=msg;x.className='toast show'+(err?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>x.className='toast',2400)}
function todayKst(){const p=n=>String(n).padStart(2,'0'),d=new Date(Date.now()+9*3600000);return `${d.getUTCFullYear()}-${p(d.getUTCMonth()+1)}-${p(d.getUTCDate())}`}
function applyCorrections(events,corrections){const latest=new Map(),added=[];for(const c of corrections||[]){if(c.action==='ADD'){added.push(c);continue}const k=c.event_id,prev=latest.get(k);if(k!=null&&(!prev||new Date(c.created_at)>new Date(prev.created_at)))latest.set(k,c)}const out=[];for(const e of events||[]){const c=latest.get(e.id);if(c?.action==='VOID')continue;out.push({...e,event_type:c?.action==='EDIT_TYPE'&&c.new_event_type?c.new_event_type:e.event_type,event_at:c?.action==='EDIT_TIME'&&c.new_event_at?c.new_event_at:e.event_at})}for(const c of added)out.push({id:`add_${c.id}`,employee_id:c.employee_id,event_type:c.new_event_type,event_at:c.new_event_at});return out}
async function refreshStatus(){const id=Number(el('employee').value),d=el('date').value;if(!id||!d){el('status').textContent='직원과 날짜를 선택해주세요.';return}el('status').textContent='확인 중…';try{const [s,data]=await Promise.all([rpc('admin_schedule_list',{p_from:d,p_to:d}),rpc('admin_events_with_corrections',{p_from:`${d}T00:00:00`,p_to:`${d}T23:59:59`})]);const sch=(s||[]).find(x=>Number(x.employee_id)===id);const ev=applyCorrections(data?.events||[],data?.corrections||[]).filter(x=>Number(x.employee_id)===id);let planned='예정 없음';if(sch?.status==='WORK')planned=`예정 ${String(sch.planned_start||'').slice(0,5)}–${String(sch.planned_end||'').slice(0,5)}`;else if(sch?.status==='OFF')planned='휴무';const actual=ev.length?`출퇴근 기록 ${ev.length}건`:'출퇴근 기록 없음';el('status').innerHTML=`<b>${planned}</b> · ${actual}`;}catch(e){el('status').textContent='근태 정보를 불러오지 못했습니다.'}}
async function init(){Auth.load();if(!Auth.token){location.href='index.html#admin';return}try{if(!await rpc('is_admin'))throw Error('NO_ADMIN');employees=(await rpc('admin_list_employees'))||[];el('employee').innerHTML='<option value="">직원 선택</option>'+employees.filter(x=>x.is_active!==false&&x.active!==false).map(x=>`<option value="${x.id}">${x.name}</option>`).join('');el('date').value=todayKst();}catch(e){location.href='index.html#admin';return}el('back').onclick=()=>location.href='index.html#admin';el('employee').onchange=refreshStatus;el('date').onchange=refreshStatus;document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{decision=b.dataset.decision;document.querySelectorAll('[data-decision]').forEach(x=>x.classList.toggle('on',x===b))});el('save').onclick=async()=>{const id=Number(el('employee').value),d=el('date').value;if(!id||!d)return toast('직원과 날짜를 선택해주세요.',true);try{const r=await rpc('admin_absence_decision_set',{p_employee_id:id,p_work_date:d,p_decision:decision,p_note:el('note').value.trim()||null});if(!r?.ok)throw Error(r?.error||'SAVE_FAILED');toast('판정을 저장했습니다.')}catch(e){toast('판정을 저장하지 못했습니다.',true)}}}
init();