const CONFIG={SUPABASE_URL:"https://waluhdgqhwjjwmflhrle.supabase.co",SUPABASE_ANON_KEY:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhbHVoZGdxaHdqandtZmxocmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2MTg4NjAsImV4cCI6MjEwMzE5NDg2MH0.-UugGE05V70Ecw__UdIZpWJr2mDYmLfV7mh_lR-U9Mw"};
const Auth={token:null,load(){try{this.token=JSON.parse(localStorage.getItem('baekeok_auth'))?.access_token||null}catch(_){this.token=null}return this.token}};
async function rpc(fn,args={}){const r=await fetch(`${CONFIG.SUPABASE_URL}/rest/v1/rpc/${fn}`,{method:'POST',headers:{apikey:CONFIG.SUPABASE_ANON_KEY,Authorization:`Bearer ${Auth.token||CONFIG.SUPABASE_ANON_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(args)});const t=await r.text();if(!r.ok)throw new Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):null}
const BE={isAdmin:()=>rpc('is_admin'),employees:()=>rpc('admin_list_employees'),list:(d)=>rpc('admin_schedule_list',{p_from:d,p_to:d}),set:(id,d,status,start,end)=>rpc('admin_schedule_set',{p_employee_id:id,p_work_date:d,p_status:status,p_start:start||null,p_end:end||null,p_memo:null}),del:(id,d)=>rpc('admin_schedule_delete',{p_employee_id:id,p_work_date:d})};
const el=id=>document.getElementById(id),busy=new Set();function toast(m,err=false){const x=el('toast');x.textContent=m;x.className='toast show'+(err?' err':'');clearTimeout(toast.t);toast.t=setTimeout(()=>x.className='toast',2200)}function p(n){return String(n).padStart(2,'0')}function todayKst(){const d=new Date(Date.now()+9*3600000);return `${d.getUTCFullYear()}-${p(d.getUTCMonth()+1)}-${p(d.getUTCDate())}`}function shiftDate(iso,delta){const [y,m,d]=iso.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+delta));return `${x.getUTCFullYear()}-${p(x.getUTCMonth()+1)}-${p(x.getUTCDate())}`}
function rowHtml(e,w){const st=w?.status||'',ss=w?.planned_start?String(w.planned_start).slice(0,5):'',se=w?.planned_end?String(w.planned_end).slice(0,5):'';return `<section class="card" data-emp="${e.id}"><div class="empname">${e.name}</div><div class="field"><label>근무 상태</label><select class="status"><option value="">미등록</option><option value="WORK" ${st==='WORK'?'selected':''}>근무</option><option value="OFF" ${st==='OFF'?'selected':''}>휴무</option></select></div><div class="time-range" ${st==='WORK'?'':'hidden'}><div class="time-field"><input class="start" type="time" value="${ss}"></div><span class="time-sep">~</span><div class="time-field"><input class="end" type="time" value="${se}"></div></div><div class="row-actions"><button class="btn primary save">저장</button>${w?'<button class="btn danger del">등록취소</button>':''}</div></section>`}
async function load(){const d=el('date').value,app=el('app');app.innerHTML='<div class="loading">불러오는 중…</div>';try{const [emps,rows]=await Promise.all([BE.employees(),BE.list(d)]);const active=(emps||[]).filter(x=>x.is_active!==false&&x.active!==false);app.innerHTML=`<div class="employee-grid">${active.map(e=>rowHtml(e,(rows||[]).find(r=>Number(r.employee_id)===Number(e.id)))).join('')}</div>`||'<div class="empty">활성 직원이 없습니다.</div>';bindRows()}catch(e){console.error('[daily-schedule-load]',e);app.innerHTML='<div class="empty">일정을 불러오지 못했습니다.<br><button class="btn" id="retry">다시 시도</button></div>';el('retry').onclick=load}}
function bindRows(){document.querySelectorAll('[data-emp]').forEach(card=>{const id=Number(card.dataset.emp),status=card.querySelector('.status'),range=card.querySelector('.time-range'),start=card.querySelector('.start'),end=card.querySelector('.end'),save=card.querySelector('.save');status.onchange=()=>{const on=status.value==='WORK';range.hidden=!on;if(on&&!start.value&&!end.value){start.value='09:00';end.value='18:00'}};save.onclick=async()=>{if(busy.has(id))return;const st=status.value,d=el('date').value;if(!st)return toast('근무 상태를 선택하세요.',true);if(st==='WORK'&&(!start.value||!end.value||start.value===end.value))return toast('근무시간을 확인하세요.',true);busy.add(id);save.disabled=true;try{const r=await BE.set(id,d,st,start.value,end.value);if(r?.ok===false)throw Error(r.error||'SAVE_FAILED');toast('일정을 저장했습니다.');await load()}catch(e){toast('저장하지 못했습니다.',true)}finally{busy.delete(id);save.disabled=false}};const del=card.querySelector('.del');if(del)del.onclick=async()=>{if(busy.has(id))return;if(!confirm('이 일정 등록을 취소할까요?'))return;busy.add(id);del.disabled=true;try{await BE.del(id,el('date').value);toast('일정을 등록취소했습니다.');await load()}catch(e){toast('등록취소하지 못했습니다.',true)}finally{busy.delete(id);del.disabled=false}}})}
function bindStaticControls(){el('date').value=el('date').value||todayKst();el('back').onclick=()=>location.href='index.html#admin';el('date').onchange=load;el('prevDay').onclick=()=>{el('date').value=shiftDate(el('date').value,-1);load()};el('nextDay').onclick=()=>{el('date').value=shiftDate(el('date').value,1);load()};el('today').onclick=()=>{el('date').value=todayKst();load()}}
async function init(){Auth.load();bindStaticControls();if(!Auth.token)return location.href='index.html#admin';load()}
init();