import fs from 'node:fs';
let pass=0,fail=0;const ok=(n,c)=>{if(c){pass++;console.log('✓ '+n)}else{fail++;console.error('✗ '+n)}};
const c=fs.readFileSync('employment_contracts_ia_v4.js','utf8');
const mh=fs.readFileSync('planned_monthly_schedule.html','utf8');
const g=fs.readFileSync('monthly_schedule_contract_guard.js','utf8');
const m=fs.readFileSync('monthly_schedule.js','utf8');
ok('first contract detected before save',c.includes('const isFirstContract=!c?.id'));
ok('first contract save returns to origin after readback',c.includes("if(isFirstContract)setTimeout(returnToContractOrigin,700)")&&c.indexOf("READBACK_FAILED")<c.indexOf("setTimeout(returnToContractOrigin,700)"));
ok('existing contract edit stays on page',!c.includes('if(!isFirstContract)setTimeout'));
ok('employee/admin back context reused',c.includes("from==='employees'")&&c.includes('focus=employees&resume=${resume}#admin')&&c.includes('index.html?resume=${resume}#admin'));
ok('monthly guard loaded after existing schedule code',mh.indexOf('monthly_schedule.js')<mh.indexOf('monthly_schedule_contract_guard.js'));
ok('contract source uses existing employment bundle RPC',g.includes("admin_employment_bundle"));
ok('hourly weekday comparison is contract workday based',g.includes("c.payroll_type!=='HOURLY'")&&g.includes('contract_id')&&g.includes('weekday(date)'));
ok('contract exception does not hard-block schedule',g.includes('대타·추가근무 일정으로 등록할 수 있습니다.'));
ok('mobile save requires explicit exception confirmation',g.includes("#saveWizard")&&g.includes('confirm(')&&g.includes('계약 근무요일은 주휴 기준이 되는 계약조건'));
ok('desktop save also guarded',g.includes("#saveDraft"));
ok('planned schedule payload semantics untouched',m.includes("op:'SET'")&&m.includes("scheduleBatch(payload)"));
ok('guard does not mutate attendance or payroll',!g.includes('attendance_events')&&!g.includes('calcPayroll')&&!g.includes('admin_close_payroll'));
console.log(`\nContract return/schedule guard QA: ${pass} passed, ${fail} failed`);if(fail)process.exit(1);
