import fs from 'node:fs';import assert from 'node:assert/strict';
const index=fs.readFileSync('index.html','utf8');
const contract=fs.readFileSync('employment_contracts_v3.js','utf8');
const docs=fs.readFileSync('employment_contract_docs_v1.js','utf8');
const ia=fs.readFileSync('employment_contracts_ia_v4.js','utf8');
assert(!index.includes("계약 미등록</span>"));
assert(!index.includes("계약서 없음</span>"));
assert(index.includes("contractNeedsAttention"));
assert(index.includes('class="contract-alert"'));
assert(index.includes(".badge.work, .badge.success{"));
assert(contract.includes("function requiredAlert(missing)"));
assert(contract.includes("시급 ${requiredAlert(!c?.hourly_wage)}"));
assert(contract.includes("계약 근무요일 ${requiredAlert(!c||workdaysFor(c.id).length===0)}"));
assert(contract.includes("월급액 ${requiredAlert(!c?.monthly_salary)}"));
assert(contract.includes("공제율 (%) ${requiredAlert(c?.business_deduction_rate==null)}"));
assert(contract.includes("el('legacy').textContent='';"));
assert(ia.includes("입사일 ${requiredAlert(true)}"));
assert(docs.includes('id="contractDocRequired"'));
assert(docs.includes("setDocAttention(!(docs||[]).length&&!S.pendingContractFile)"));
console.log('contract attention badge QA PASS');

assert(contract.includes("function refreshRequiredAlerts()"));
assert(contract.includes("addEventListener('input',refreshRequiredAlerts)"));
assert(contract.includes("S.workdays.size===0"));
assert(contract.includes("refreshRequiredAlerts()"));
