import fs from 'node:fs';
let pass=0,fail=0;const ok=(n,c)=>{if(c){pass++;console.log('✓ '+n)}else{fail++;console.error('✗ '+n)}};
const html=fs.readFileSync('planned_monthly_schedule.html','utf8');
const css=fs.readFileSync('monthly_calendar_state_v1.css','utf8');
const js=fs.readFileSync('monthly_calendar_state_v1.js','utf8');
ok('state css is loaded after contract guard',html.indexOf('monthly_schedule_contract_guard.css')<html.indexOf('monthly_calendar_state_v1.css'));
ok('state js is loaded after contract guard',html.indexOf('monthly_schedule_contract_guard.js')<html.indexOf('monthly_calendar_state_v1.js'));
ok('legend uses contract vocabulary and one unified selection state',js.includes('미계약일')&&js.includes('계약일')&&js.includes('저장된 일정')&&js.includes('선택됨')&&!js.includes('현재 선택')&&!js.includes('계약 외 선택'));
ok('selected dates get one shared check marker',js.includes("check.className='selection-check'")&&js.includes("check.textContent='✓'"));
ok('selection marker is not color-only',css.includes('.calday .selection-check')&&css.includes('border-radius:50%'));
ok('contract exception keeps orange contract-extra semantic badge',css.includes("content:'계약외'")&&css.includes('.calday.contract-extra.selected:before'));
ok('contract baseline has separate semantic palette',css.includes('--calendar-contract:')&&css.includes('.calday.contract-day:before'));
ok('saved schedule has separate semantic fill',css.includes('--calendar-saved-bg:')&&css.includes('.calday.saved:not(.selected)'));
ok('calendar buttons expose selected state to assistive tech',js.includes("setAttribute('aria-pressed'"));
ok('calendar buttons expose state labels',js.includes("setAttribute('aria-label'"));
ok('render wrapper has no MutationObserver loop',!js.includes('MutationObserver')&&js.includes('requestAnimationFrame(decorateCalendarStateSemantics)'));
console.log(`\nMonthly calendar state QA: ${pass} passed, ${fail} failed`);if(fail)process.exit(1);
