import fs from 'node:fs';import assert from 'node:assert/strict';
const mod=fs.readFileSync('payroll_contract_authority_v1.js','utf8');
const loader=fs.readFileSync('payroll_elapsed_weeks_v1.js','utf8');
const index=fs.readFileSync('index.html','utf8');
let pass=0;const t=(n,f)=>{f();pass++;console.log('PASS',n)};
t('main html loads elapsed-week bootstrap directly',()=>{assert(index.includes('payroll_elapsed_weeks_v1.js?v='));assert(loader.includes('DOMContentLoaded'));assert(loader.includes('payroll_contract_authority_v1.js?v='))});
t('payroll reads authoritative employment bundle through owned authenticated RPC',()=>{assert(mod.includes("adminRpc('admin_employment_bundle'"));assert(!mod.includes("rpc('admin_employment_bundle'"));assert(mod.includes('function adminRpc'));assert(mod.includes('grant_type=refresh_token'));assert(mod.includes('c.hourly_wage'));assert(mod.includes('c.weekly_contracted_minutes'));assert(mod.includes('c.business_deduction_rate'))});
t('recurring duplicate monthly overrides are excluded from calculation',()=>{assert(mod.includes('function safeOverride'));assert(!/out\.wage_override/.test(mod));assert(!/out\.juhyu_hours_override/.test(mod));assert(!/out\.tax_rate_override/.test(mod));assert(mod.includes('juhyu_weeks_override'));assert(mod.includes('adjust_amount'))});
t('existing finalized payroll computation remains authoritative',()=>{assert(mod.includes('const baseComputeMonthPayroll=computeMonthPayroll'));assert(mod.includes('const R=await baseComputeMonthPayroll(ym)'));assert(mod.includes('Base computeMonthPayroll is authoritative'))});
t('weekly holiday candidate requires at least 900 contracted minutes',()=>{assert(mod.includes('weeklyMinutes>=900?weeklyMinutes/60/5:0'))});
t('monthly payroll is implemented while four-insurance remains policy-blocked',()=>{assert(mod.includes("mode:'MONTHLY'"));assert(mod.includes('monthly_salary'));assert(mod.includes('4대보험 공제 계산정책 미확정'))});
t('contract gaps and mid-month incompatible changes fail visibly instead of guessing',()=>{assert(mod.includes('계약기간 밖 실근무'));assert(mod.includes('월중 계약조건 변경'))});
t('blocked payroll keeps authoritative contract state without repeating contract prose on summary cards',()=>{assert(mod.includes('contract:displayContract'));assert(mod.includes('급여 확인 필요'));assert(!mod.includes("s.textContent=contractSummary(rec.contract)"))});
t('missing contracts block payroll instead of falling back to duplicate legacy wage fields',()=>{assert(mod.includes("mode:'MISSING_CONTRACT'"));assert(mod.includes('계약조건 미등록 · 급여 계산 보류'));assert(!mod.includes("mode:'LEGACY'"));assert(mod.includes("edit.textContent='계약 등록'"));assert(mod.includes('employment_contracts.html?employee='))});
t('payroll close is blocked while any contract or attendance issue remains',()=>{assert(mod.includes("!['CONTRACT','MONTHLY'].includes(r.contractMode)||Number(r.issues||0)>0"));assert(mod.includes('close.disabled=!!blockers.length'));assert(mod.includes('확인필요 항목을 먼저 해결하세요.'))});
t('contract-backed payroll removes duplicate basic edit and month adjustment hides recurring contract fields',()=>{assert(mod.includes('else edit.remove()'));assert(mod.includes("['maWage','maJh','maTax']"))});
t('current payroll refreshes while visible without full redraw',()=>{assert(mod.includes('setInterval(patchLive,10000)'));assert(mod.includes('window.__patchPayrollLiveValues=patchLive'));assert(!mod.includes('setInterval(refresh,60000)'));assert(mod.includes('visibilitychange'))});
console.log(`Payroll contract authority V2 QA: ${pass} PASS`);
