import fs from 'node:fs';
const js=fs.readFileSync('payroll_contract_authority_v1.js','utf8');
const loader=fs.readFileSync('payroll_elapsed_weeks_v1.js','utf8');
const need=(ok,msg)=>{if(!ok)throw new Error(msg)};
need(js.includes('payroll-gross-hero'),'gross payroll hero must exist');
need(js.includes('payroll-tax-label')&&js.includes('(세전)'),'gross amount must carry a quiet tax label');
need(js.includes('payroll-gross-value'),'gross value must have dedicated dominant styling');
need(js.includes("issueBadge=head?.querySelector('.badge.issue');if(issueBadge)issueBadge.remove()"),'issue count badge must be removed');
need(js.includes("card.classList.toggle('payroll-has-issue'"),'issue state must remain machine-visible');
need(js.includes('font-size:2rem'),'employee gross value must be visually dominant');need(js.includes('font-size:3rem'),'total gross value must be larger than employee gross');need(js.includes('fmtHM(rec.sec)')&&js.includes(' 근무'),'worked time must be the only normal support line');
need(/payroll_contract_authority_v1\.js\?v=\d+[a-z]?/.test(loader),'loader must cache-bust payroll authority UX');
console.log('gross-first payroll UX QA PASS');
