import fs from 'node:fs';import assert from 'node:assert/strict';
const js=fs.readFileSync('substitution_v2.js','utf8'),html=fs.readFileSync('substitution.html','utf8'),bridge=fs.readFileSync('substitution_test_attendance_bridge_v1.js','utf8');
assert(js.includes("TEST_KEY='baekeok_test_mode_v1'")&&js.includes("TEST_SUB_KEY='baekeok_test_substitution_v1'"));
assert(js.includes("if(testOn())")&&js.includes("pin!=='0000'"));
assert(js.includes("localStorage.setItem(TEST_SUB_KEY"));
const testCreate=js.indexOf("if(testOn())",js.indexOf('async function sendReq'));const prodCreate=js.indexOf('substitution_request_create',testCreate);assert(testCreate>0&&prodCreate>testCreate);
assert(html.includes('testSubBanner')&&/substitution_v2\.js\?v=\d+[a-z]/.test(html));
assert(html.includes('substitution_test_attendance_bridge_v1.js'));
assert(bridge.includes("MODE='baekeok_test_mode_v1'")&&bridge.includes("SUB='baekeok_test_substitution_v1'"));
assert(bridge.includes('actual_minutes')&&bridge.includes("'COMPLETED'")&&bridge.includes("'FAILED'"));
console.log('substitution TEST isolation V1 QA PASS');